create table student
(student_id number Primary Key,
student_first_name varchar2(50) not null,
student_last_name varchar2(60) not null,
student_level varchar2(1) not null);


CREATE TABLE TEACHER
(TEACHER_ID NUMBER PRIMARY KEY,
TEACHER_FIRST_NAME VARCHAR2(50),
TEACHER_LAST_NAME VARCHAR2(60),
SALARY NUMBER);


CREATE TABLE DORM_ROOM 
(DORM_ROOM_ID NUMBER PRIMARY KEY,
BUILDING_NAME VARCHAR2(50) NOT NULL,
COST NUMBER);


CREATE TABLE TERM
(TERM_ID NUMBER PRIMARY KEY,
TERM_DESC VARCHAR2(50) NOT NULL,
TERM_BEGIN_DATE DATE NOT NULL,
TERM_END_DATE DATE NOT NULL);


CREATE TABLE CLASS
(CLASS_NUMBER NUMBER PRIMARY KEY,
CLASS_NAME VARCHAR2(50) NOT NULL,
SUBJECT_ID NUMBER NOT NULL,
PREREQ_IND VARCHAR2(50));


