INSERT INTO DORM_ROOM
(DORM_ROOM_ID, BUILDING_ID, COST)
VALUES
('ABC123','Searcy',125.25);

INSERT INTO DORM_ROOM
(DORM_ROOM_ID, BUILDING_ID, COST)
VALUES
('DEF234','Wood',75.89);

INSERT INTO DORM_ROOM
(DORM_ROOM_ID, BUILDING_ID, COST)
VALUES
('GHI567','Columbia',145.15);

INSERT INTO STUDENT
(STUDENT_ID, STUDENT_FIRST_NAME, STUDENT_LAST_NAME, STUDENT_TYPE, FK_DORM_ROOM_ID)
VALUES
(12345678,'James','Joyce','F','ABC123');

INSERT INTO STUDENT
(STUDENT_ID, STUDENT_FIRST_NAME, STUDENT_LAST_NAME, STUDENT_TYPE, FK_DORM_ROOM_ID)
VALUES
(23456789,'Ernest','Hemingway','S','DEF234');

INSERT INTO STUDENT
(STUDENT_ID, STUDENT_FIRST_NAME, STUDENT_LAST_NAME, STUDENT_TYPE, FK_DORM_ROOM_ID)
VALUES
(34567890,'Zelda','Fitzgerald','J',NULL);

INSERT INTO TEXTBOOK
(TEXTBOOK_ID, TEXTBOOK_TITLE, FK_STUDENT_ID)
VALUES
('123-45-6789','Database Design and Implementation',12345678);

INSERT INTO TEXTBOOK
(TEXTBOOK_ID, TEXTBOOK_TITLE, FK_STUDENT_ID)
VALUES
('345-67-8901','Systems Analysis and Design',23456789);

INSERT INTO TEXTBOOK
(TEXTBOOK_ID, TEXTBOOK_TITLE, FK_STUDENT_ID)
VALUES
('678-90-1234','Refreshing Calculus',NULL);
