-- BUCKFAST USE CASES --

-- 1
-- A customer makes purchases in two of the stores.  You need to track which 
-- of the stores the purchase was made in, as well as the product, the number 
-- of products sold (ie. 5 cinnamon candles), and the price of the product.  
-- You will also need to update the inventory of the store to reflect the 
-- purchase.

-- Find which customers have made multiple purchases.
SELECT COUNT(FK_CUSTOMER_ID), FK_CUSTOMER_ID  FROM BASALE_TRANSACTION GROUP BY FK_CUSTOMER_ID
HAVING COUNT(FK_CUSTOMER_ID) > 1 ORDER BY FK_CUSTOMER_ID ;

--WHOLE CUSTOMER TRANSACTION
SELECT C.CUSTOMER_ID, C.FIRST_NAME, C.LAST_NAME, ST.SALE_TRANSACTION_ID, ST.TRANSACTION_DATE, LI.QUANTITY AS PURCHASED_AMT, P.PRODUCT_NAME, P.PRODUCT_PRICE, SILI.QUANTITY AS QOH, B.BUSINESS_NAME
FROM BACUSTOMER C
JOIN BASALE_TRANSACTION ST ON ST.FK_CUSTOMER_ID = C.CUSTOMER_ID
JOIN BATRANSACTION_LINE_ITEM LI ON ST.SALE_TRANSACTION_ID = LI.FK_SALE_TRANSACTION_ID
JOIN BAPRODUCT P ON P.PRODUCT_ID =  LI.FK_PRODUCT_ID
JOIN BASTORE_INVENTORY_LINEITEM SILI ON SILI.FK_PRODUCT_ID = P.PRODUCT_ID
JOIN BASHIPMENT SHIP ON SHIP.SHIPMENT_ID = SILI.FK_SHIPMENT_ID
JOIN BASTORE_INVENTORY SI ON SI.STORE_INVENTORY_ID = SHIP.FK_STORE_INVENTORY_ID
JOIN BASTORE_ENTITY E ON E.BUSINESS_ID = SI.FK_BUSINESS_ID
JOIN BABUSINESS B ON B.BUSINESS_ID = E.BUSINESS_ID
WHERE C.CUSTOMER_ID = 'C1004'
;
--QOH
SELECT SUM(SILI.QUANTITY - LI.QUANTITY), P.PRODUCT_ID, P.PRODUCT_NAME
FROM BACUSTOMER C
JOIN BASALE_TRANSACTION ST ON ST.FK_CUSTOMER_ID = C.CUSTOMER_ID
JOIN BATRANSACTION_LINE_ITEM LI ON ST.SALE_TRANSACTION_ID = LI.FK_SALE_TRANSACTION_ID
JOIN BAPRODUCT P ON P.PRODUCT_ID =  LI.FK_PRODUCT_ID
JOIN BASTORE_INVENTORY_LINEITEM SILI ON SILI.FK_PRODUCT_ID = P.PRODUCT_ID
JOIN BASHIPMENT SHIP ON SHIP.SHIPMENT_ID = SILI.FK_SHIPMENT_ID
JOIN BASTORE_INVENTORY SI ON SI.STORE_INVENTORY_ID = SHIP.FK_STORE_INVENTORY_ID
WHERE C.CUSTOMER_ID = 'C1004'
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
;



UPDATE BASTORE_INVENTORY_LINEITEM
SET QUANTITY = (QUANTITY - (SELECT LI.QUANTITY
                            FROM BACUSTOMER C
                            JOIN BASALE_TRANSACTION ST ON ST.FK_CUSTOMER_ID = C.CUSTOMER_ID
                            JOIN BATRANSACTION_LINE_ITEM LI ON ST.SALE_TRANSACTION_ID = LI.FK_SALE_TRANSACTION_ID
                            JOIN BAPRODUCT P ON P.PRODUCT_ID =  LI.FK_PRODUCT_ID
                            JOIN BASTORE_INVENTORY_LINEITEM SILI ON SILI.FK_PRODUCT_ID = P.PRODUCT_ID
                            WHERE C.CUSTOMER_ID = 'C1004'
                            )
                )
WHERE STORE_INVENTORY_LINEITEM_ID = SILI.STORE_INVENTORY_LINEITEM_ID
;







SELECT CUSTOMER.CUST_FNAME, PRODUCT.PRODUCT_NAME, PRODUCT.PRICE,INVOICE_LINE_ITEM.QUANTITY_SOLD, SHOP.SHOP_NAME
FROM CUSTOMER
JOIN SALE ON CUSTOMER.CUSTOMER_ID = SALE.FK_CUST_ID
JOIN INVOICE_LINE_ITEM ON SALE.SALE_ID = INVOICE_LINE_ITEM.FK_SALE_ID
JOIN PRODUCT_INVENTORY ON INVOICE_LINE_ITEM.FK_INVENTORY_ON_INVOICE = PRODUCT_INVENTORY.PRODUCT_INVENTORY_ID
JOIN PRODUCT ON PRODUCT_INVENTORY.FK_PRODUCT_IN_INV = PRODUCT.PRODUCT_ID
JOIN SHOP ON PRODUCT_INVENTORY.FK_SHOP_WITH_INV = SHOP.SHOP_ID
WHERE CUSTOMER.CUSTOMER_ID = 10;

UPDATE PRODUCT_INVENTORY
SET QUANTITY = (QUANTITY - (SELECT INVOICE_LINE_ITEM.QUANTITY_SOLD
                            FROM INVOICE_LINE_ITEM
                            JOIN SALE ON INVOICE_LINE_ITEM.FK_SALE_ID = SALE.SALE_ID  
                            WHERE SALE.FK_CUST_ID = 10
                            ORDER BY INVOICE_LINE_ITEM.QUANTITY_SOLD));
















SELECT LI.QUANTITY
FROM BACUSTOMER C
JOIN BASALE_TRANSACTION ST ON ST.FK_CUSTOMER_ID = C.CUSTOMER_ID
JOIN BATRANSACTION_LINE_ITEM LI ON ST.SALE_TRANSACTION_ID = LI.FK_SALE_TRANSACTION_ID
WHERE C.CUSTOMER_ID = 'C1004'

SELECT SILI.STORE_INVENTORY_LINEITEM_ID
FROM BACUSTOMER C
JOIN BASALE_TRANSACTION ST ON ST.FK_CUSTOMER_ID = C.CUSTOMER_ID
JOIN BATRANSACTION_LINE_ITEM LI ON ST.SALE_TRANSACTION_ID = LI.FK_SALE_TRANSACTION_ID
JOIN BAPRODUCT P ON P.PRODUCT_ID =  LI.FK_PRODUCT_ID
JOIN BASTORE_INVENTORY_LINEITEM SILI ON SILI.FK_PRODUCT_ID = P.PRODUCT_ID
WHERE C.CUSTOMER_ID = 'C1004'





-- 2
-- TOTAL NUMBER OF SALES FOR A SINGLE STORE FOR THE MONTH OF JUNE 2019

SELECT TO_CHAR(SUM(TLI.QUANTITY * P.PRODUCT_PRICE), 'FML99G999D00','NLS_NUMERIC_CHARACTERS = ''.,'' NLS_CURRENCY=€') AS TOTAL_SALES  
FROM BASALE_TRANSACTION T
JOIN BATRANSACTION_LINE_ITEM TLI ON T.SALE_TRANSACTION_ID = TLI.FK_SALE_TRANSACTION_ID
JOIN BAPRODUCT P ON P.PRODUCT_ID = TLI.FK_PRODUCT_ID
JOIN BASTORE_INVENTORY_LINEITEM SILI ON P.PRODUCT_ID = SILI.FK_PRODUCT_ID
JOIN BASHIPMENT SHIP ON SILI.FK_SHIPMENT_ID = SHIP.SHIPMENT_ID
JOIN BASTORE_INVENTORY SI ON SHIP.FK_STORE_INVENTORY_ID = SI.STORE_INVENTORY_ID
JOIN BASTORE_ENTITY SE ON SI.FK_BUSINESS_ID = SE.BUSINESS_ID
JOIN BABUSINESS ON SE.BUSINESS_ID = BABUSINESS.BUSINESS_ID
WHERE T.TRANSACTION_DATE BETWEEN TO_DATE('6-1-19', 'MM-DD-YY') AND TO_DATE('6-30-19', 'MM-DD-YY')
AND BUSINESS_NAME = 'GIFT SHOP';


-- 3
-- A new employee is hired for the Grange Restaurant.  You will need to track
-- their hours and their pay rate per hour.  Calculate their salary for the 
-- week of June 1 through June 8.
-- NEWEST EMPLOYEE AT THE GRANGE

SELECT SHI.START_DATE_TIME - SHI.END_DATE_TIME
FROM BAASSIGNED_SCHEDULE ASSI
JOIN BASHIFT SHI ON SHI.FK_ASSIGNED_SCHEDULE_ID = ASSI.ASSIGNED_SCHEDULE_ID
JOIN BAEMPLOYEE E ON E.EMPLOYEE_ID = SHI.FK_EMPLOYEE_ID
WHERE ASSI.FK_BUSINESS_ID = 'R1'
AND SHI.FK_EMPLOYEE_ID = (SELECT BAEMPLOYEE.EMPLOYEE_ID FROM BAEMPLOYEE 
  WHERE BAEMPLOYEE.HIRE_DATE = (SELECT MAX(HIRE_DATE) FROM BAEMPLOYEE));
  
  
-- HOURS WORKED BETWEEN JUNE 1 AND JUNE 8
(SELECT SHI.END_DATE_TIME - SHI.START_DATE_TIME
FROM BAASSIGNED_SCHEDULE ASSI
JOIN BASHIFT SHI ON SHI.FK_ASSIGNED_SCHEDULE_ID = ASSI.ASSIGNED_SCHEDULE_ID
JOIN BAEMPLOYEE E ON E.EMPLOYEE_ID = SHI.FK_EMPLOYEE_ID
WHERE ASSI.FK_BUSINESS_ID = 'R1'
AND ASSI.START_DATE >= TO_DATE('6-1-19', 'MM-DD-YY')
AND ASSI.END_DATE <= TO_DATE('6-8-19', 'MM-DD-YY')
AND SHI.FK_EMPLOYEE_ID = (SELECT BAEMPLOYEE.EMPLOYEE_ID FROM BAEMPLOYEE 
  WHERE BAEMPLOYEE.HIRE_DATE = (SELECT MAX(HIRE_DATE) FROM BAEMPLOYEE))
);


select sum((SELECT END_DATE_TIME - START_DATE_TIME
  FROM BAASSIGNED_SCHEDULE ASSI
  JOIN BASHIFT SHI ON SHI.FK_ASSIGNED_SCHEDULE_ID = ASSI.ASSIGNED_SCHEDULE_ID
  JOIN BAEMPLOYEE E ON E.EMPLOYEE_ID = SHI.FK_EMPLOYEE_ID
  WHERE ASSI.FK_BUSINESS_ID = 'R1'  -- The Restaurant
  AND ASSI.START_DATE >= TO_DATE('6-1-19', 'MM-DD-YY')
  AND ASSI.END_DATE   <= TO_DATE('6-8-19', 'MM-DD-YY')
  AND SHI.FK_EMPLOYEE_ID    = 'L107')
 
* 
(SELECT PAY_RATE
  FROM BAPAYCHECK
  WHERE FK_EMPLOYEE_ID = 'L107')) 


from dual
;
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
--




-- 4
-- A Visitor makes a reservation for June 1, 2019 to June 14, 2019 for one of 
-- the Guest Houses, and a monk must be assigned for each of those weeks.  
-- Display the Visitor name, the Guest house, and the monk assigned for each week.
SELECT C.FIRST_NAME AS CUSTOMER_FIRST, C.LAST_NAME AS CUSTOMER_LAST, 
  BUSINESS_NAME, E.FIRST_NAME AS EMP_FIRST, E.LAST_NAME AS EMP_LAST, 
  ASSI.START_DATE AS SCHEDULE_START, ASSI.END_DATE AS SCHEDULE_END,
  R.DATE_START AS RESERVARTION_START_DATE, R.DATE_END AS RESERVATION_END_DATE
FROM BARESERVATION R
JOIN BAGUESTHOUSE_RESERVATION GHR ON R.RESERVATION_ID = GHR.FK_RESERVATION_ID
JOIN BAGUESTHOUSE_ROOM ROOM ON ROOM.GUESTHOUSE_ROOM_ID = GHR.FK_GUESTHOUSE_ROOM_ID
JOIN BAGUESTHOUSE GH  ON GH.BUSINESS_ID = ROOM.FK_BUSINESS_ID
JOIN BABUSINESS ON BABUSINESS.BUSINESS_ID = GH.BUSINESS_ID
JOIN BAASSIGNED_SCHEDULE ASSI ON ASSI.FK_BUSINESS_ID = GH.BUSINESS_ID
JOIN BASHIFT ON ASSI.ASSIGNED_SCHEDULE_ID = BASHIFT.FK_ASSIGNED_SCHEDULE_ID
JOIN BAEMPLOYEE E ON BASHIFT.FK_EMPLOYEE_ID = E.EMPLOYEE_ID
JOIN BACUSTOMER C ON C.CUSTOMER_ID = R.FK_CUSTOMER_ID
WHERE R.DATE_START = TO_DATE('6-1-19', 'MM-DD-YY') 
  AND R.DATE_END = TO_DATE('6-14-19','MM-DD-YY');


-- 5 -- WHAT COLUMNS NEED TO BE INCLUDED
-- The Abbot wants to know how many distinct guests have reservations at the 
-- abbey from June 1 to August 31 in 2019.  Even if I have stayed at the abbey
-- twice, I should only be counted once.
SELECT DISTINCT C.CUSTOMER_ID, C.FIRST_NAME, C.LAST_NAME
FROM BACUSTOMER C 
JOIN BARESERVATION R ON R.FK_CUSTOMER_ID = C.CUSTOMER_ID
JOIN BAGUESTHOUSE_RESERVATION GHR ON GHR.FK_RESERVATION_ID = R.RESERVATION_ID
WHERE R.DATE_START >= TO_DATE('6-1-19', 'MM-DD-YY')
  AND R.DATE_END <= TO_DATE('8-31-19', 'MM-DD-YY');


-- 6
-- The Abbott wants to know how many rooms do NOT have reservations at the
-- abbey on Saturday, June 8, 2019.

SELECT COUNT(ROOM.GUESTHOUSE_ROOM_ID) AS AVAILABLE_ROOMS
FROM BAGUESTHOUSE_ROOM ROOM
LEFT JOIN BAGUESTHOUSE_RESERVATION GHR ON ROOM.GUESTHOUSE_ROOM_ID = GHR.FK_GUESTHOUSE_ROOM_ID
LEFT JOIN BARESERVATION R ON R.RESERVATION_ID = GHR.FK_RESERVATION_ID
WHERE ROOM.GUESTHOUSE_ROOM_ID NOT IN 
  (SELECT BAGHR.GUESTHOUSE_ROOM_ID 
    FROM BAGUESTHOUSE_ROOM BAGHR 
    JOIN BAGUESTHOUSE_RESERVATION BARES ON BARES.FK_GUESTHOUSE_ROOM_ID = BAGHR.GUESTHOUSE_ROOM_ID
    JOIN BARESERVATION RESERVATION ON RESERVATION.RESERVATION_ID = BARES.FK_RESERVATION_ID
    WHERE TO_DATE('6-8-19', 'MM-DD-YY') BETWEEN RESERVATION.DATE_START AND RESERVATION.DATE_END);


-- 7
-- The Abbott wants to know all room numbers, as well as those customer names 
-- that are staying at the monastery on Friday, June 7, 2019.
SELECT GHR.ROOM_NAME, C.FIRST_NAME, C.LAST_NAME, BAR.DATE_START, BAR.DATE_END
FROM BAGUESTHOUSE_ROOM GHR
JOIN BAGUESTHOUSE_RESERVATION GHRES ON GHRES.FK_GUESTHOUSE_ROOM_ID = GHR.GUESTHOUSE_ROOM_ID
JOIN BARESERVATION BAR ON BAR.RESERVATION_ID = GHRES.FK_RESERVATION_ID
JOIN BACUSTOMER C ON C.CUSTOMER_ID = BAR.FK_CUSTOMER_ID
WHERE TO_DATE('6-7-19', 'MM-DD-YY') BETWEEN BAR.DATE_START AND BAR.DATE_END;


-- 8
-- The Abbot would like to know if there are any visitors that have made 
-- repeat visits (MORE THAN 1) so they can direct market efforts toward them. 
-- include customer address

SELECT COUNT(C.CUSTOMER_ID) AS CUSTOMER_VISIT_COUNT, C.CUSTOMER_ID
FROM BASALE_TRANSACTION BAST 
JOIN BACUSTOMER C ON C.CUSTOMER_ID = BAST.FK_CUSTOMER_ID
JOIN BARESERVATION BAR ON C.CUSTOMER_ID = BAR.FK_CUSTOMER_ID
GROUP BY C.CUSTOMER_ID
HAVING COUNT(C.CUSTOMER_ID) >= 2;



-- 9
-- Each week inventory must be taken to determine if anything needs to be 
-- reordered.  Using a single SQL query, determine which products are in need
-- of reordering.  This means you have to calculate not only what you have
-- in stock, but what you have sold this week for a particular product.

-- COLLECTION OF LINEITEMS
SELECT COUNT(BATLI.FK_PRODUCT_ID) AS COUNT_PURCHASED, P.PRODUCT_ID, SILI.QUANTITY AS QOH
FROM BAPRODUCT P
JOIN BATRANSACTION_LINE_ITEM BATLI ON BATLI.FK_PRODUCT_ID =  P.PRODUCT_ID
JOIN BASTORE_INVENTORY_LINEITEM SILI ON SILI.FK_PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_ID, SILI.QUANTITY
ORDER BY P.PRODUCT_ID;

-- LIST OF PRODUCTS TO ORDER
SELECT P.PRODUCT_ID, SUM(QOH - COUNT_PURCHASED) AS AMT_ON_HAND, COUNT_PURCHASED AS AMT_TO_ORDER
FROM BAPRODUCT P
JOIN
(
  SELECT COUNT(BATLI.FK_PRODUCT_ID) AS COUNT_PURCHASED, P.PRODUCT_ID, SILI.QUANTITY AS QOH
  FROM BAPRODUCT P
  JOIN BATRANSACTION_LINE_ITEM BATLI ON BATLI.FK_PRODUCT_ID =  P.PRODUCT_ID
  JOIN BASTORE_INVENTORY_LINEITEM SILI ON SILI.FK_PRODUCT_ID = P.PRODUCT_ID
  GROUP BY P.PRODUCT_ID, SILI.QUANTITY
) PLI
ON PLI.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_ID, COUNT_PURCHASED
ORDER BY P.PRODUCT_ID;








-- 10




