--------------------------------------------------------------------------------
--------------------------------------DROP--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

Drop table BACustomer_Address_Type cascade constraints;
Drop table BACustomer cascade constraints;
Drop table BACustomer_Address cascade constraints;
Drop table BASale_Transaction cascade constraints;
Drop table BAReservation cascade constraints;
Drop table BASchedule cascade constraints;
Drop table BAEmployee_Type cascade constraints;
Drop table BAEmployee cascade constraints;
Drop table BAShift cascade constraints;
Drop table BAGuestHouse cascade constraints;
Drop table BAGuestHouse_Room cascade constraints;
Drop table BAGuestHouse_Reservation cascade constraints;
Drop table BAStore_Business_Type cascade constraints;
Drop table BAStore_Entity cascade constraints;
Drop table BAPayroll cascade constraints;
Drop table BAPaycheck cascade constraints;
Drop table BARestaurant_Reservation cascade constraints;
Drop table BASTORE_INVENTORY cascade constraints;
Drop table BAProduct_Type cascade constraints;
Drop table BAProduct cascade constraints;
Drop table BAVendor cascade constraints;
Drop table BASTORE_INVENTORY_LineItem cascade constraints;
Drop table BATransaction_Line_Item cascade constraints;


--------------------------------------------------------------------------------
--------------------------------------CREATE--------------------------------------------------------------------------------
--------------------------------------------------------------------------------


CREATE TABLE BACustomer_Address_Type (
  Address_Type_ID number(10) not null,
  Address_Type_Description varchar2(100) not null,
  PRIMARY KEY (Address_Type_ID)
);

CREATE TABLE BACustomer (
  Customer_ID varchar2(15) not null,
  First_Name varchar2(100) not null,
  Last_Name varchar2(100) not null,
  PRIMARY KEY (Customer_ID)
);

CREATE TABLE BACustomer_Address (
  Customer_Address_ID number(10) not null,
  Street_Address varchar2(100) not null,
  City varchar2(50) not null,
  State varchar2(50) not null,
  Zipcode varchar2(20) not null,
  FK_Customer_ID varchar2(15) not null,
  FK_Customer_Address_Type_ID number(10) not null,
  PRIMARY KEY (Customer_Address_ID),
  FOREIGN KEY (FK_Customer_ID) REFERENCES BACustomer (Customer_ID),
  FOREIGN KEY (FK_Customer_Address_Type_ID) REFERENCES BACustomer_Address_Type (Address_Type_ID)
);

CREATE TABLE BASale_Transaction (
  Sale_Transaction_ID number(10)  not null,
  FK_Customer_ID varchar2(15) not null,
  Transaction_Date Date not null,
  Transaction_Amount number(8,2) not null,
  PRIMARY KEY (Sale_Transaction_ID),
  FOREIGN KEY (FK_Customer_ID) REFERENCES BACustomer (Customer_ID)
);

CREATE TABLE BAReservation (
  Reservation_ID number(10) not null,
  FK_Customer_ID varchar2(15)  not null,
  DATE_START Date not null,
  DATE_END Date not null,
  Reservation_Price number(8,2) not null,
  PRIMARY KEY (Reservation_ID),
  FOREIGN KEY (FK_Customer_ID) REFERENCES BACustomer (Customer_ID)
);

CREATE TABLE BASchedule (
  Schedule_ID number(10) not null,
  START_DATE Date not null,
  END_DATE Date not null,
  PRIMARY KEY (Schedule_ID)
);

CREATE TABLE BAEmployee_Type (
  Employee_Type_ID number(10) not null,
  Employee_Type_Name varchar2(100) not null,
  Employee_Type_Description varchar2(200) not null,
  PRIMARY KEY (Employee_Type_ID)
);

CREATE TABLE BAEmployee (
  Employee_ID varchar2(15) not null,
  FK_Employee_Type_ID number(10) not null,
  First_Name varchar2(50) not null,
  Last_Name varchar2(50) not null,
  PRIMARY KEY (Employee_ID),
  FOREIGN KEY (FK_Employee_Type_ID) REFERENCES BAEmployee_Type (Employee_Type_ID)
);

CREATE TABLE BAShift (
  Shift_ID number(10) not null,
  FK_Employee_ID varchar2(15) not null,
  FK_Schedule_ID number(10) not null,
  Start_Time varchar2(4) not null,
  End_Time varchar2(4) not null,
  PRIMARY KEY (Shift_ID),
  FOREIGN KEY (FK_Employee_ID) REFERENCES BAEmployee (Employee_ID), 
  FOREIGN KEY (FK_Schedule_ID) REFERENCES BASchedule (Schedule_ID)
);

CREATE TABLE BAGuestHouse (
  GuestHouse_ID varchar(15) not null,
  Num_of_Room number(3) not null,
  Max_Occupancy number(3) not null,
  FK_Schedule_ID number(10) not null,
  GuestHouse_Name varchar2(100) not null,
  PRIMARY KEY (GuestHouse_ID), 
  FOREIGN KEY (FK_Schedule_ID) REFERENCES BASchedule (Schedule_ID)
);

CREATE TABLE BAGuestHouse_Room (
  GuestHouse_Room_ID varchar2(15) not null,
  FK_GuestHouse_ID varchar2(15) not null,
  Room_Name varchar2(50) not null,
  Room_Occupancy number(2) not null,
  Room_Price number(8,2) not null,
  PRIMARY KEY (GuestHouse_Room_ID),
  FOREIGN KEY (FK_GuestHouse_ID) REFERENCES BAGuestHouse (GuestHouse_ID)
);

CREATE TABLE BAGuestHouse_Reservation (
  GuestHouse_Reservation_ID varchar2(15) not null,
  FK_GuestHouse_Room_ID varchar2(15) not null,
  FK_Reservation_ID number(10) not null,
  Guest_Count number(2) not null,
  PRIMARY KEY (GuestHouse_Reservation_ID),
  FOREIGN KEY (FK_GuestHouse_Room_ID) REFERENCES BAGuestHouse_Room (GuestHouse_Room_ID),
  FOREIGN KEY (FK_Reservation_ID) REFERENCES BAReservation (Reservation_ID)
);

CREATE TABLE BAStore_Business_Type (
  Store_Business_Type_ID number(4) not null,
  Store_Business_Type_Name varchar2(100) not null,
  Store_Business_Type_Descript varchar2(200) not null,
  PRIMARY KEY (Store_Business_Type_ID)
);

CREATE TABLE BAStore_Entity (
  Store_ID varchar2(15) not null,
  FK_Schedule_ID number(10) not null,
  Store_Name varchar2(100) not null,
  FK_Store_Business_Type_ID number(4) not null,
  PRIMARY KEY (Store_ID),
  FOREIGN KEY (FK_Schedule_ID) REFERENCES BASchedule (Schedule_ID),
  FOREIGN KEY (FK_Store_Business_Type_ID) REFERENCES BAStore_Business_Type (Store_Business_Type_ID)
);

CREATE TABLE BAPayroll (
  Payroll_ID number(10) not null,
  FK_Store_ID varchar2(15) not null,
  PayPeriod_START_DATE Date not null,
  PayPeriod_END_DATE Date not null,
  PRIMARY KEY (Payroll_ID),
  FOREIGN KEY (FK_Store_ID) REFERENCES BAStore_Entity (Store_ID)
);

CREATE TABLE BAPaycheck (
  Paycheck_ID number(10) not null,
  FK_Employee_ID varchar2(15) not null,
  FK_Payroll_ID number(10) not null,
  Hours_Worked number(6,2) not null,
  Pay_Rate number(6,2) not null,
  PRIMARY KEY (Paycheck_ID),
  FOREIGN KEY (FK_Employee_ID) REFERENCES BAEmployee (Employee_ID),
  FOREIGN KEY (FK_Payroll_ID) REFERENCES BAPayroll (Payroll_ID)
);

CREATE TABLE BARestaurant_Reservation (
  Restaurant_Reservation_ID varchar(15) not null,
  FK_Store_ID varchar2(15) not null,
  FK_Reservation_ID number(10) not null,
  Num_of_Guests number(3) not null,
  PRIMARY KEY (Restaurant_Reservation_ID),
  FOREIGN KEY (FK_Store_ID) REFERENCES BAStore_Entity (Store_ID),
  FOREIGN KEY (FK_Reservation_ID) REFERENCES BAReservation (Reservation_ID)
);

CREATE TABLE BASTORE_INVENTORY (
  STORE_INVENTORY_ID varchar(15) not null,
  FK_Store_ID varchar(15) not null,
  DATE_RECEIVED Date  not null,
  Shipment_Order varchar(20) not null,
  PRIMARY KEY (STORE_INVENTORY_ID),
  FOREIGN KEY (FK_Store_ID) REFERENCES BAStore_Entity (Store_ID)
);

CREATE TABLE BAProduct_Type (
  Product_Type_ID varchar2(15) not null,
  Product_Type_Name varchar2(100) not null,
  Product_Type_Description varchar2(300),
  PRIMARY KEY (Product_Type_ID)
);

CREATE TABLE BAProduct (
  Product_ID varchar2(15) not null,
  FK_Product_Type_ID varchar2(15) not null,
  Product_Name varchar2(100) not null,
  Product_Description varchar2(300),
  Product_Price number(8,2) not null,
  Product_Cost number(8,2) not null,
  PRIMARY KEY (Product_ID)
);

CREATE TABLE BAVendor (
  Vendor_ID varchar2(15) not null,
  VENDOR_NAME varchar2(100) not null,
  PRIMARY KEY (Vendor_ID)
);

CREATE TABLE BASTORE_INVENTORY_LineItem (
  STORE_INVENTORY_LineItem_ID number(10) not null,
  FK_ProductID varchar2(15) not null,
  FK_STORE_INVENTORY_ID varchar2(15) not null,
  FK_Vendor_ID varchar2(15) not null,
  Quantity number(4) not null,
  PRIMARY KEY (STORE_INVENTORY_LineItem_ID),
  FOREIGN KEY (FK_ProductID) REFERENCES BAProduct (Product_ID),
  FOREIGN KEY (FK_STORE_INVENTORY_ID) REFERENCES BASTORE_INVENTORY (STORE_INVENTORY_ID),
  FOREIGN KEY (FK_Vendor_ID) REFERENCES BAVendor (Vendor_ID)
);

CREATE TABLE BATransaction_Line_Item (
  Transaction_Line_Item_ID number(10) not null,
  FK_Product_ID varchar2(15),
  FK_Sale_Transaction_ID number(10),
  Quantity number(4),
  Price number(8,2),
  PRIMARY KEY (Transaction_Line_Item_ID),
  FOREIGN KEY (FK_Product_ID) REFERENCES BAProduct (Product_ID),
  FOREIGN KEY (FK_Sale_Transaction_ID) REFERENCES BASale_Transaction (Sale_Transaction_ID)
);


--------------------------------------------------------------------------------
--------------------------------------INSERT--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

-- ADDRESS_TYPE
INSERT ALL
INTO BACUSTOMER_ADDRESS_TYPE (ADDRESS_TYPE_ID, ADDRESS_TYPE_DESCRIPTION) VALUES (1,	'Home')
INTO BACUSTOMER_ADDRESS_TYPE (ADDRESS_TYPE_ID, ADDRESS_TYPE_DESCRIPTION) VALUES (2,	'Business')
INTO BACUSTOMER_ADDRESS_TYPE (ADDRESS_TYPE_ID, ADDRESS_TYPE_DESCRIPTION) VALUES (3,	'Shipping')
INTO BACUSTOMER_ADDRESS_TYPE (ADDRESS_TYPE_ID, ADDRESS_TYPE_DESCRIPTION) VALUES (4,	'Postal Box')
SELECT * FROM DUAL;

-- CUSTOMER
INSERT ALL
INTO BACUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME) VALUES ('C1004',	'Angela',	'Merkel')
INTO BACUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME) VALUES ('C1005',	'Tissaia',	'deVries')
INTO BACUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME) VALUES ('C1006',	'Ada',	'Lovelace')
INTO BACUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME) VALUES ('C1007',	'Arya',	'Stark')
INTO BACUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME) VALUES ('C1008',	'Yennefer',	'Vengerberg')
INTO BACUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME) VALUES ('C1009',	'Diana',	'Prince')
INTO BACUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME) VALUES ('C1010',	'Kara',	'Zor-el')
INTO BACUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME) VALUES ('C1011',	'Carol',	'Danvers')
INTO BACUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME) VALUES ('C1012',	'Barbara',	'Kingsolver')
INTO BACUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME) VALUES ('C1013',	'Taelia',	'Fordragon')
INTO BACUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME) VALUES ('C1014',	'Jaina',	'Proudmoore')
SELECT * FROM DUAL;

-- CUSTOMER_ADDRESS
INSERT ALL
INTO BACUSTOMER_ADDRESS (CUSTOMER_ADDRESS_ID, STREET_ADDRESS, CITY, STATE, ZIPCODE, FK_CUSTOMER_ID, FK_CUSTOMER_ADDRESS_TYPE_ID) VALUES (2601004,	'Prenzlauer Allee 6',	'Templin',	'Brandenburg',	'17268',	'C1004',	2)
INTO BACUSTOMER_ADDRESS (CUSTOMER_ADDRESS_ID, STREET_ADDRESS, CITY, STATE, ZIPCODE, FK_CUSTOMER_ID, FK_CUSTOMER_ADDRESS_TYPE_ID) VALUES (2601005,	'13-1 Waterford Place',	'Aretuza',	'Thanedd',	'1267',	'C1005',	2)
INTO BACUSTOMER_ADDRESS (CUSTOMER_ADDRESS_ID, STREET_ADDRESS, CITY, STATE, ZIPCODE, FK_CUSTOMER_ID, FK_CUSTOMER_ADDRESS_TYPE_ID) VALUES (2601006,	'Woking 6NL',	'Ockham',	'Surrey',	'GU23',	'C1006',	1)
INTO BACUSTOMER_ADDRESS (CUSTOMER_ADDRESS_ID, STREET_ADDRESS, CITY, STATE, ZIPCODE, FK_CUSTOMER_ID, FK_CUSTOMER_ADDRESS_TYPE_ID) VALUES (2601007,	'165 E 7th Ave',	'Temple',	'Bravos',	'23TEMP',	'C1007',	4)
INTO BACUSTOMER_ADDRESS (CUSTOMER_ADDRESS_ID, STREET_ADDRESS, CITY, STATE, ZIPCODE, FK_CUSTOMER_ID, FK_CUSTOMER_ADDRESS_TYPE_ID) VALUES (2601008,	'13-3 Waterford Place',	'Aretuza',	'Thanedd',	'1267',	'C1008',	3)
INTO BACUSTOMER_ADDRESS (CUSTOMER_ADDRESS_ID, STREET_ADDRESS, CITY, STATE, ZIPCODE, FK_CUSTOMER_ID, FK_CUSTOMER_ADDRESS_TYPE_ID) VALUES (2601009,	'Royal Quarters #1',	'Paradise Island',	'Themyscira',	'630 88',	'C1009',	1)
INTO BACUSTOMER_ADDRESS (CUSTOMER_ADDRESS_ID, STREET_ADDRESS, CITY, STATE, ZIPCODE, FK_CUSTOMER_ID, FK_CUSTOMER_ADDRESS_TYPE_ID) VALUES (2601010,	'1961 Eastern Rim',	'Argo City',	'Krypton',	'279123',	'C1010',	1)
INTO BACUSTOMER_ADDRESS (CUSTOMER_ADDRESS_ID, STREET_ADDRESS, CITY, STATE, ZIPCODE, FK_CUSTOMER_ID, FK_CUSTOMER_ADDRESS_TYPE_ID) VALUES (2601011,	'303 Hinkle Lake Road',	'Boston',	'Massachusetts',	'02114',	'C1011',	3)
INTO BACUSTOMER_ADDRESS (CUSTOMER_ADDRESS_ID, STREET_ADDRESS, CITY, STATE, ZIPCODE, FK_CUSTOMER_ID, FK_CUSTOMER_ADDRESS_TYPE_ID) VALUES (2601012,	'719 Main St',	'Apalachin',	'New York',	'13732',	'C1012',	1)
INTO BACUSTOMER_ADDRESS (CUSTOMER_ADDRESS_ID, STREET_ADDRESS, CITY, STATE, ZIPCODE, FK_CUSTOMER_ID, FK_CUSTOMER_ADDRESS_TYPE_ID) VALUES (2601013,	'478 Military Ward Dr',	'Boralus',	'Kul Tiras',	'90004',	'C1013',	1)
INTO BACUSTOMER_ADDRESS (CUSTOMER_ADDRESS_ID, STREET_ADDRESS, CITY, STATE, ZIPCODE, FK_CUSTOMER_ID, FK_CUSTOMER_ADDRESS_TYPE_ID) VALUES (2601014,	'1000 Capital Way',	'Boralus',	'Kul Tiras',	'90005',	'C1014',	3)
SELECT * FROM DUAL;

-- SALE_TRANSACTION
INSERT ALL
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT) VALUES (3331004,	'C1004',	TO_DATE('6-1-19', 'MM-DD-YY'),	40.00)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT) VALUES (3331005,	'C1005',	TO_DATE('6-4-19', 'MM-DD-YY'),	10.50)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT) VALUES (3331006,	'C1006',	TO_DATE('6-7-19', 'MM-DD-YY'),	37.89)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT) VALUES (3331007,	'C1007',  TO_DATE('6-11-19', 'MM-DD-YY'),	123.54)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT) VALUES (3331008,	'C1008',	TO_DATE('6-15-19', 'MM-DD-YY'),	14.56)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT) VALUES (3331009,	'C1009',	TO_DATE('6-21-19', 'MM-DD-YY'),	87.13)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT) VALUES (3331010,	'C1010',	TO_DATE('6-28-19', 'MM-DD-YY'),	63.99)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT) VALUES (3331011,	'C1011',	TO_DATE('7-1-19', 'MM-DD-YY'),	82.09)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT) VALUES (3331012,	'C1012',	TO_DATE('7-2-19', 'MM-DD-YY'),	13.05)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT) VALUES (3331013,	'C1013',	TO_DATE('7-5-19', 'MM-DD-YY'),	45.45)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT) VALUES (3331014,	'C1014',	TO_DATE('7-8-19', 'MM-DD-YY'),	55.52)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT) VALUES (3331015,	'C1004',	TO_DATE('7-9-12', 'MM-DD-YY'),	23.23)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT) VALUES (3331016,	'C1005',	TO_DATE('7-13-19', 'MM-DD-YY'),	9.67)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT) VALUES (3331017,	'C1006',	TO_DATE('7-17-19', 'MM-DD-YY'),	33.87)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT) VALUES (3331018,	'C1007',	TO_DATE('7-20-19', 'MM-DD-YY'),	90.05)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT) VALUES (3331019,	'C1008',	TO_DATE('7-27-19', 'MM-DD-YY'),	72.89)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT) VALUES (3331020,	'C1009',	TO_DATE('7-31-19', 'MM-DD-YY'),	145.65)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT) VALUES (3331021,	'C1010',	TO_DATE('8-1-19', 'MM-DD-YY'),	67.67)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT) VALUES (3331022,	'C1011',	TO_DATE('8-3-19', 'MM-DD-YY'),	65.23)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT) VALUES (3331023,	'C1012',	TO_DATE('8-5-19', 'MM-DD-YY'),	15.00)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT) VALUES (3331024,	'C1013',	TO_DATE('8-7-19', 'MM-DD-YY'),	13.25)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTION_DATE, TRANSACTION_AMOUNT) VALUES (3331025,	'C1014',	TO_DATE('8-8-19', 'MM-DD-YY'),	55.45)
SELECT * FROM DUAL;

-- RESERVATION
INSERT ALL 
INTO BARESERVATION (RESERVATION_ID, FK_CUSTOMER_ID, DATE_START, DATE_END, RESERVATION_PRICE) VALUES (450104, 'C1014',	TO_DATE('6-1-19', 'MM-DD-YY'),	TO_DATE('6-14-19', 'MM-DD-YY'),	840)
INTO BARESERVATION (RESERVATION_ID, FK_CUSTOMER_ID, DATE_START, DATE_END, RESERVATION_PRICE) VALUES (450105, 'C1012',	TO_DATE('6-2-19', 'MM-DD-YY'),	TO_DATE('6-7-19', 'MM-DD-YY'),	360)
INTO BARESERVATION (RESERVATION_ID, FK_CUSTOMER_ID, DATE_START, DATE_END, RESERVATION_PRICE) VALUES (450106,	'C1010',	TO_DATE('6-4-19', 'MM-DD-YY'), TO_DATE('6-4-19', 'MM-DD-YY'),	0)
INTO BARESERVATION (RESERVATION_ID, FK_CUSTOMER_ID, DATE_START, DATE_END, RESERVATION_PRICE) VALUES (450107,	'C1008',	TO_DATE('6-4-19', 'MM-DD-YY'),	TO_DATE('6-4-19', 'MM-DD-YY'),	0)
INTO BARESERVATION (RESERVATION_ID, FK_CUSTOMER_ID, DATE_START, DATE_END, RESERVATION_PRICE) VALUES (450108,	'C1006',	TO_DATE('6-4-19', 'MM-DD-YY'),	TO_DATE('6-10-19', 'MM-DD-YY'),	420)
INTO BARESERVATION (RESERVATION_ID, FK_CUSTOMER_ID, DATE_START, DATE_END, RESERVATION_PRICE) VALUES (450109,	'C1004',	TO_DATE('6-5-19', 'MM-DD-YY'),	TO_DATE('6-7-19', 'MM-DD-YY'),	180)
INTO BARESERVATION (RESERVATION_ID, FK_CUSTOMER_ID, DATE_START, DATE_END, RESERVATION_PRICE) VALUES (450110,	'C1013', TO_DATE('6-6-19', 'MM-DD-YY'),	TO_DATE('6-8-19', 'MM-DD-YY'),	180)
INTO BARESERVATION (RESERVATION_ID, FK_CUSTOMER_ID, DATE_START, DATE_END, RESERVATION_PRICE) VALUES (450111,	'C1011',	TO_DATE('6-10-19', 'MM-DD-YY'),	TO_DATE('6-12-19', 'MM-DD-YY'),	180)
INTO BARESERVATION (RESERVATION_ID, FK_CUSTOMER_ID, DATE_START, DATE_END, RESERVATION_PRICE) VALUES (450112,	'C1009',	TO_DATE('6-15-19', 'MM-DD-YY'),	TO_DATE('6-15-19', 'MM-DD-YY'),	0)
INTO BARESERVATION (RESERVATION_ID, FK_CUSTOMER_ID, DATE_START, DATE_END, RESERVATION_PRICE) VALUES (450113,	'C1007',	TO_DATE('6-15-19', 'MM-DD-YY'),	TO_DATE('6-25-19', 'MM-DD-YY'),	660)
INTO BARESERVATION (RESERVATION_ID, FK_CUSTOMER_ID, DATE_START, DATE_END, RESERVATION_PRICE) VALUES (450114,	'C1005',	TO_DATE('6-19-19', 'MM-DD-YY'),	TO_DATE('6-21-19', 'MM-DD-YY'),	180)
INTO BARESERVATION (RESERVATION_ID, FK_CUSTOMER_ID, DATE_START, DATE_END, RESERVATION_PRICE) VALUES (450115,	'C1011',	TO_DATE('6-20-19', 'MM-DD-YY'), TO_DATE('6-30-19', 'MM-DD-YY'),	660)
INTO BARESERVATION (RESERVATION_ID, FK_CUSTOMER_ID, DATE_START, DATE_END, RESERVATION_PRICE) VALUES (450116,	'C1008',	TO_DATE('7-3-19', 'MM-DD-YY'),	TO_DATE('7-3-19', 'MM-DD-YY'),	0)
INTO BARESERVATION (RESERVATION_ID, FK_CUSTOMER_ID, DATE_START, DATE_END, RESERVATION_PRICE) VALUES (450117,	'C1014',	TO_DATE('7-21-19', 'MM-DD-YY'),	TO_DATE('7-24-19', 'MM-DD-YY'),	240)
INTO BARESERVATION (RESERVATION_ID, FK_CUSTOMER_ID, DATE_START, DATE_END, RESERVATION_PRICE) VALUES (450118,	'C1014',	TO_DATE('7-28-19', 'MM-DD-YY'),	TO_DATE('7-29-19', 'MM-DD-YY'),	120)
INTO BARESERVATION (RESERVATION_ID, FK_CUSTOMER_ID, DATE_START, DATE_END, RESERVATION_PRICE) VALUES (450119,	'C1009',	TO_DATE('8-15-19', 'MM-DD-YY'),	TO_DATE('8-30-19', 'MM-DD-YY'),	960)
SELECT * FROM DUAL;

-- SCHEDULE
INSERT ALL
INTO BASCHEDULE (SCHEDULE_ID, START_DATE, END_DATE) VALUES (20190505,	TO_DATE('5-26-19', 'MM-DD-YY'),	TO_DATE('6-1-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, START_DATE, END_DATE) VALUES (20190506,	TO_DATE('5-26-19', 'MM-DD-YY'),	TO_DATE('5-26-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, START_DATE, END_DATE) VALUES (20190507,	TO_DATE('5-27-19', 'MM-DD-YY'),	TO_DATE('5-27-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, START_DATE, END_DATE) VALUES (20190508,	TO_DATE('5-28-19', 'MM-DD-YY'),	TO_DATE('5-28-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, START_DATE, END_DATE) VALUES (20190509,	TO_DATE('5-29-19', 'MM-DD-YY'),	TO_DATE('5-29-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, START_DATE, END_DATE) VALUES (20190510,	TO_DATE('5-30-19', 'MM-DD-YY'),	TO_DATE('5-30-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, START_DATE, END_DATE) VALUES (20190511,	TO_DATE('5-31-19', 'MM-DD-YY'),	TO_DATE('5-31-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, START_DATE, END_DATE) VALUES (20190512,	TO_DATE('6-1-19', 'MM-DD-YY'),	TO_DATE('6-1-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, START_DATE, END_DATE) VALUES (20190513,	TO_DATE('6-2-19', 'MM-DD-YY'),	TO_DATE('6-8-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, START_DATE, END_DATE) VALUES (20190514,	TO_DATE('6-2-19', 'MM-DD-YY'),	TO_DATE('6-2-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, START_DATE, END_DATE) VALUES (20190515,	TO_DATE('6-3-19', 'MM-DD-YY'),	TO_DATE('6-3-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, START_DATE, END_DATE) VALUES (20190516,	TO_DATE('6-4-19', 'MM-DD-YY'),	TO_DATE('6-4-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, START_DATE, END_DATE) VALUES (20190517,	TO_DATE('6-5-19', 'MM-DD-YY'),	TO_DATE('6-5-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, START_DATE, END_DATE) VALUES (20190518,	TO_DATE('6-6-19', 'MM-DD-YY'),	TO_DATE('6-6-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, START_DATE, END_DATE) VALUES (20190519,	TO_DATE('6-7-19', 'MM-DD-YY'),	TO_DATE('6-7-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, START_DATE, END_DATE) VALUES (20190520,	TO_DATE('6-8-19', 'MM-DD-YY'),	TO_DATE('6-8-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, START_DATE, END_DATE) VALUES (20190521,	TO_DATE('6-9-19', 'MM-DD-YY'),	TO_DATE('6-15-18', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, START_DATE, END_DATE) VALUES (20190522,	TO_DATE('6-9-19', 'MM-DD-YY'),	TO_DATE('6-9-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, START_DATE, END_DATE) VALUES (20190523, TO_DATE('6-10-19', 'MM-DD-YY'),	TO_DATE('6-10-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, START_DATE, END_DATE) VALUES (20190524,	TO_DATE('6-11-19', 'MM-DD-YY'),	TO_DATE('6-11-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, START_DATE, END_DATE) VALUES (20190525, TO_DATE('6-12-19', 'MM-DD-YY'),	TO_DATE('6-12-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, START_DATE, END_DATE) VALUES (20190526,	TO_DATE('6-13-19', 'MM-DD-YY'),	TO_DATE('6-13-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, START_DATE, END_DATE) VALUES (20190527,	TO_DATE('6-14-19', 'MM-DD-YY'),	TO_DATE('6-14-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, START_DATE, END_DATE) VALUES (20190528, TO_DATE('6-15-19', 'MM-DD-YY'),	TO_DATE('6-15-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, START_DATE, END_DATE) VALUES (20190529,	TO_DATE('6-16-19', 'MM-DD-YY'),	TO_DATE('6-22-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, START_DATE, END_DATE) VALUES (20190530,	TO_DATE('6-16-19', 'MM-DD-YY'),	TO_DATE('6-16-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, START_DATE, END_DATE) VALUES (20190531,	TO_DATE('6-17-19', 'MM-DD-YY'),	TO_DATE('6-17-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, START_DATE, END_DATE) VALUES (20190532,	TO_DATE('6-18-19', 'MM-DD-YY'),	TO_DATE('6-18-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, START_DATE, END_DATE) VALUES (20190533,	TO_DATE('6-19-19', 'MM-DD-YY'),	TO_DATE('6-19-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, START_DATE, END_DATE) VALUES (20190534,	TO_DATE('6-20-19', 'MM-DD-YY'),	TO_DATE('6-20-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, START_DATE, END_DATE) VALUES (20190535,	TO_DATE('6-21-19', 'MM-DD-YY'),	TO_DATE('6-21-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, START_DATE, END_DATE) VALUES (20190536,	TO_DATE('6-22-19', 'MM-DD-YY'),	TO_DATE('6-22-19', 'MM-DD-YY'))
SELECT * FROM DUAL;

-- EMPLOYEE_TYPE
INSERT ALL
INTO BAEMPLOYEE_TYPE (EMPLOYEE_TYPE_ID, EMPLOYEE_TYPE_NAME, EMPLOYEE_TYPE_DESCRIPTION) VALUES (1,	'Monk',	'Tenant of the Abbey')
INTO BAEMPLOYEE_TYPE (EMPLOYEE_TYPE_ID, EMPLOYEE_TYPE_NAME, EMPLOYEE_TYPE_DESCRIPTION) VALUES (2,	'Nun',	'Sister of the Church')
INTO BAEMPLOYEE_TYPE (EMPLOYEE_TYPE_ID, EMPLOYEE_TYPE_NAME, EMPLOYEE_TYPE_DESCRIPTION) VALUES (3,	'Layperson',	'Paid Employee')
SELECT * FROM DUAL;

-- EMPLOYEE
INSERT ALL
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('M100',	1,	'Warren',	'Townsend')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('M101',	1,	'Kenneth',	'Aun')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('M102',	1,	'Adrian',	'Harper')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('M103',	1,	'Russell',	'Kim')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('M104',	1,	'Cornelius',	'Walters')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('M105',	1,	'Emanuel',	'Gill')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('N100',	2,	'Rene',	'Boyden')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('M106',	1,	'Nick',	'MacGuire')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('M107',	1,	'Larry',	'Montalvo')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('L100',	3,	'Sylvester',	'Garm')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('M108',	1,	'Brian',	'Gladden')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('N101',	2,	'Terry',	'Aiken')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('M109',	1,	'Fernando',	'Vasquez')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('L101',	3,	'Brandon',	'Conklin')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('M110',	1,	'Andres',	'Duarte')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('M111',	1,	'Oliver',	'Vo')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('L102',	3,	'Paul',	'Tejada')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('L103',	3,	'Richelle',	'Bunn')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('L104',	3,	'Willene',	'Sotchiev')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('M112',	1,	'Mathew',	'Ballard')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('M113',	1,	'Lorenzo',	'Lamb')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('M114',	1,	'Orlando',	'White')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('M115',	1,	'Jerry',	'Hernandez')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('M116',	1,	'Geoffrey',	'Summer')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('M117',	1,	'Alfons',	'Fuller')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('M118',	1,	'Archie',	'Santos')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('M119',	1,	'Joel',	'Morries')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('M120',	1,	'Sam',	'Cannon')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('M121',	1,	'Philip',	'Williamson')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('M122',	1,	'Chad',	'Krum')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('M123',	1,	'Robert',	'Ngando')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('N102',	2,	'Cecilia',	'Laise')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('N103',	2,	'Roberta',	'Grange')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('N104',	2,	'Nina',	'Fjord')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('L105',	3,	'Nan',	'King')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('L106',	3,	'Sarah',	'Turtle')
INTO BAEMPLOYEE (EMPLOYEE_ID, FK_EMPLOYEE_TYPE_ID, FIRST_NAME, LAST_NAME) VALUES ('L107',	3,	'Gloria',	'Kiev')
select * from dual;

-- SHIFT
INSERT ALL
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (201,	'M100',	20190505,	'0000',	'2359')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (202,	'M101',	20190505,	'0000',	'2359')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (203,	'M102',	20190505,	'0000',	'2359')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (204,	'M103',	20190505,	'0000',	'2359')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (205,	'M104',	20190505,	'0000',	'2359')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (206,	'M105',	20190505,	'0000',	'2359')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (207,	'M106',	20190505,	'0000',	'2359')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (208,	'M107',	20190505,	'0000',	'2359')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (209,	'M108',	20190505,	'0000',	'2359')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (210,	'M109',	20190505,	'0000',	'2359')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (211,	'M110',	20190505,	'0000',	'2359')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (212,	'M111',	20190505,	'0000',	'2359')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (213,	'N100',	20190506,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (214,	'N100',	20190507,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (215,	'N100',	20190508,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (216,	'N100',	20190509,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (217,	'N100',	20190510,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (218,	'L100',	20190506,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (219,	'L100', 20190507,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (220,	'L100',	20190508,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (221,	'L100',	20190509,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (222,	'L100',	20190510,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (223,	'N101',	20190506,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (224,	'N101',	20190507,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (225,	'N101',	20190508,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (226,	'N101',	20190509,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (227,	'N101',	20190510,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (228,	'L101',	20190506,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (229,	'L101',	20190507,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (230,	'L101',	20190508,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (231,	'L101',	20190509,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (232,	'L101',	20190510,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (233,	'N102',	20190506,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (234,	'N102',	20190507,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (235,	'N102',	20190508,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (236,	'N102',	20190509,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (240,	'N102',	20190510,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (241,	'L102',	20190506,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (242,	'L102',	20190507,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (243,	'L102',	20190508,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (244,	'L102',	20190509,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (245,	'L102',	20190510,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (246,	'N103',	20190506,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (247,	'N103',	20190507,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (248,	'N103',	20190508,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (249,	'N103',	20190509,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (250,	'N103',	20190510,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (251,	'L103',	20190506,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (252,	'L103', 20190507,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (253,	'L103',	20190508,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (254,	'L103',	20190509,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (255,	'L103',	20190510,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (256,	'M112',	20190511,	'1000',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (267,	'M113',	20190511,	'1000',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (268,	'M114',	20190511,	'1000',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (269,	'M115',	20190511,	'1000',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (270,	'M112',	20190512,	'1000',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (271,	'M113',	20190512,	'1000',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (272,	'M114',	20190512,	'1000',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (273,	'M115',	20190512,	'1000',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (274,	'M112',	20190513,	'0000',	'2359')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (275,	'M113',	20190513,	'0000',	'2359')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (276,	'M114',	20190513,	'0000',	'2359')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (277,	'M115',	20190513,	'0000',	'2359')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (278,	'M116',	20190513,	'0000',	'2359')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (279,	'M117', 20190513,	'0000',	'2359')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (280,	'M118', 20190513,	'0000',	'2359')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (281,	'M119',	20190513,	'0000',	'2359')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (282,	'M120',	20190513,	'0000',	'2359')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (283,	'M121',	20190513,	'0000',	'2359')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (284,	'M122',	20190513,	'0000',	'2359')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (285,	'M123',	20190513,	'0000',	'2359')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (286,	'N104',	20190514,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (287,	'N104',	20190515,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (288,	'N104',	20190516,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (289,	'N104',	20190517,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (290,	'N104',	20190518,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (291,	'L104',	20190514,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (292,	'L104',	20190515,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (293,	'L104',	20190516,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (294,	'L104',	20190517,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (295,	'L104',	20190518,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (296,	'N101',	20190514,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (297,	'N101',	20190515,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (298,	'N101',	20190516,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (299,	'N101', 20190517,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (300,	'N101',	20190518,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (301,	'L105',	20190514,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (302,	'L105',	20190515,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (303,	'L105',	20190516,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (304,	'L105',	20190517,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (305,	'L105',	20190518,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (306,	'N102',	20190514,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (307,	'N102',	20190515,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (308,	'N102',	20190516,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (309,	'N102',	20190517,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (310,	'N102',	20190518,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (311,	'L106',	20190514,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (312,	'L106',	20190515,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (313,	'L106',	20190516,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (314,	'L106',	20190517,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (315,	'L106',	20190518,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (316,	'N103',	20190514,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (317,	'N103',	20190515,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (318,	'N103',	20190516,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (319,	'N103',	20190517,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (320,	'N103',	20190518,	'0800',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (321,	'L107',	20190514,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (322,	'L107',	20190515,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (323,	'L107',	20190516,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (324,	'L107',	20190517,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (325,	'L107',	20190518,	'1000',	'1800')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (326,	'M100',	20190519,	'1000',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (327,	'M101',	20190519,	'1000',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (328,	'M102',	20190519,	'1000',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (329,	'M103',	20190519,	'1000',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (330,	'M100',	20190520,	'1000',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (331,	'M101',	20190520,	'1000',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (332,	'M102',	20190520,	'1000',	'1600')
INTO BASHIFT (SHIFT_ID, FK_EMPLOYEE_ID, FK_SCHEDULE_ID, START_TIME, END_TIME) VALUES (333,	'M103',	20190520,	'1000',	'1600')
select * from dual;

-- GuestHouse
INSERT ALL
INTO BAGUESTHOUSE (GUESTHOUSE_ID, NUM_OF_ROOM, MAX_OCCUPANCY, FK_SCHEDULE_ID, GUESTHOUSE_NAME) VALUES ('1',	6,	30,	20190513,	'Peter')
INTO BAGUESTHOUSE (GUESTHOUSE_ID, NUM_OF_ROOM, MAX_OCCUPANCY, FK_SCHEDULE_ID, GUESTHOUSE_NAME) VALUES ('2',	6,	30,	20190513,	'Paul')
INTO BAGUESTHOUSE (GUESTHOUSE_ID, NUM_OF_ROOM, MAX_OCCUPANCY, FK_SCHEDULE_ID, GUESTHOUSE_NAME) VALUES ('3',	6,	30,	20190513,	'Mary')
INTO BAGUESTHOUSE (GUESTHOUSE_ID, NUM_OF_ROOM, MAX_OCCUPANCY, FK_SCHEDULE_ID, GUESTHOUSE_NAME) VALUES ('4',	6,	30,	20190513,	'John')
INTO BAGUESTHOUSE (GUESTHOUSE_ID, NUM_OF_ROOM, MAX_OCCUPANCY, FK_SCHEDULE_ID, GUESTHOUSE_NAME) VALUES ('5',	6,	30,	20190513,	'Jacob')
INTO BAGUESTHOUSE (GUESTHOUSE_ID, NUM_OF_ROOM, MAX_OCCUPANCY, FK_SCHEDULE_ID, GUESTHOUSE_NAME) VALUES ('6',	6,	30,	20190513,	'Cecilia')
INTO BAGUESTHOUSE (GUESTHOUSE_ID, NUM_OF_ROOM, MAX_OCCUPANCY, FK_SCHEDULE_ID, GUESTHOUSE_NAME) VALUES ('7',	6,	30,	20190513,	'Heimer')
INTO BAGUESTHOUSE (GUESTHOUSE_ID, NUM_OF_ROOM, MAX_OCCUPANCY, FK_SCHEDULE_ID, GUESTHOUSE_NAME) VALUES ('8',	6,	30,	20190513,	'Esther')
INTO BAGUESTHOUSE (GUESTHOUSE_ID, NUM_OF_ROOM, MAX_OCCUPANCY, FK_SCHEDULE_ID, GUESTHOUSE_NAME) VALUES ('9',	6,	30,	20190513,	'Francis')
INTO BAGUESTHOUSE (GUESTHOUSE_ID, NUM_OF_ROOM, MAX_OCCUPANCY, FK_SCHEDULE_ID, GUESTHOUSE_NAME) VALUES ('10', 6,	30,	20190513,	'Magdalena')
INTO BAGUESTHOUSE (GUESTHOUSE_ID, NUM_OF_ROOM, MAX_OCCUPANCY, FK_SCHEDULE_ID, GUESTHOUSE_NAME) VALUES ('11',	6,	30,	20190513,	'Theresa')
INTO BAGUESTHOUSE (GUESTHOUSE_ID, NUM_OF_ROOM, MAX_OCCUPANCY, FK_SCHEDULE_ID, GUESTHOUSE_NAME) VALUES ('12',	6,	30,	20190513,	'David')
SELECT * FROM DUAL;

-- GuestHouse_Room
INSERT ALL
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('1',	'1',	'Rm 1',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('2',	'1',	'Rm 2',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('3',	'1',	'Rm 3',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('4',	'1',	'Rm 4',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('5',	'1',	'Rm 5',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('6',	'1',	'Rm 6',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('7',	'2',	'Rm 7',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('8',	'2',	'Rm 8',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('9',	'2',	'Rm 9',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('10',	'2',	'Rm 10',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('11',	'2',	'Rm 11',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('12',	'2',	'Rm 12',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('13',	'3',	'Rm 13',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('14',	'3',	'Rm 14',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('15',	'3',	'Rm 15',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('16',	'3',	'Rm 16',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('17',	'3',	'Rm 17',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('18',	'3',	'Rm 18',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('19',	'4',	'Rm 19',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('20',	'4',	'Rm 20',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('21',	'4',	'Rm 21',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('22',	'4',	'Rm 22',	5,  60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('23',	'4',	'Rm 23',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('24',	'4',	'Rm 24',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('25',	'5',	'Rm 25',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('26',	'5',	'Rm 26',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('27',	'5',	'Rm 27',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('28',	'5',	'Rm 28',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('29',	'5',	'Rm 29',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('30',	'5',	'Rm 30',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('31',	'6',	'Rm 31',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('32',	'6',	'Rm 32', 	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('33',	'6',	'Rm 33',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('34',	'6',	'Rm 34',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('35',	'6',	'Rm 35',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('36',	'6',	'Rm 36',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('37',	'7',	'Rm 37',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('38',	'7',	'Rm 38',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('39',	'7',	'Rm 39',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('40',	'7',	'Rm 40',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('41',	'7',	'Rm 41',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('42',	'7',	'Rm 42',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('43',	'8',	'Rm 43',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('44',	'8',	'Rm 44',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('45',	'8',	'Rm 45',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('46',	'8',	'Rm 46',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('47',	'8',	'Rm 47',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('48',	'8',	'Rm 48',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('49',	'9',	'Rm 49',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('50',	'9',	'Rm 50',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('51',	'9',	'Rm 51',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('52',	'9',	'Rm 52',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('53',	'9',	'Rm 53',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('54',	'9',	'Rm 54',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('55',	'10',	'Rm 55',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('56',	'10', 'Rm 56',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('57',	'10',	'Rm 57',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('58',	'10',	'Rm 58',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('59',	'10',	'Rm 59',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('60',	'10',	'Rm 60',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('61',	'11',	'Rm 61',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('62',	'11',	'Rm 62',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('63',	'11',	'Rm 63',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('64',	'11',	'Rm 64',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('65',	'11',	'Rm 65',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('66',	'11',	'Rm 66',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('67',	'12',	'Rm 67',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('68',	'12',	'Rm 68',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('69',	'12',	'Rm 69',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('70',	'12',	'Rm 70',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('72',	'12',	'Rm 72',	5,	60.00)
INTO BAGUESTHOUSE_ROOM (GUESTHOUSE_ROOM_ID, FK_GUESTHOUSE_ID, ROOM_NAME, ROOM_OCCUPANCY, ROOM_PRICE) VALUES ('73',	'12',	'Rm 73',	5,	60.00)
SELECT * FROM DUAL;

-- GUESTHOUSE_RESERVATION

INSERT ALL
INTO BAGUESTHOUSE_RESERVATION (GUESTHOUSE_RESERVATION_ID, FK_GUESTHOUSE_ROOM_ID, FK_RESERVATION_ID, GUEST_COUNT) VALUES ('GHR001',	'14',	450104,	2)
INTO BAGUESTHOUSE_RESERVATION (GUESTHOUSE_RESERVATION_ID, FK_GUESTHOUSE_ROOM_ID, FK_RESERVATION_ID, GUEST_COUNT) VALUES ('GHR002',	'33',	450105,	2)
INTO BAGUESTHOUSE_RESERVATION (GUESTHOUSE_RESERVATION_ID, FK_GUESTHOUSE_ROOM_ID, FK_RESERVATION_ID, GUEST_COUNT) VALUES ('GHR003',	'61',	450108,	2)
INTO BAGUESTHOUSE_RESERVATION (GUESTHOUSE_RESERVATION_ID, FK_GUESTHOUSE_ROOM_ID, FK_RESERVATION_ID, GUEST_COUNT) VALUES ('GHR004',	'63',	450109,	2)
INTO BAGUESTHOUSE_RESERVATION (GUESTHOUSE_RESERVATION_ID, FK_GUESTHOUSE_ROOM_ID, FK_RESERVATION_ID, GUEST_COUNT) VALUES ('GHR005',	'43',	450110,	2)
INTO BAGUESTHOUSE_RESERVATION (GUESTHOUSE_RESERVATION_ID, FK_GUESTHOUSE_ROOM_ID, FK_RESERVATION_ID, GUEST_COUNT) VALUES ('GHR006',	'17',	450111,	2)
INTO BAGUESTHOUSE_RESERVATION (GUESTHOUSE_RESERVATION_ID, FK_GUESTHOUSE_ROOM_ID, FK_RESERVATION_ID, GUEST_COUNT) VALUES ('GHR007',	'28',	450113,	2)
INTO BAGUESTHOUSE_RESERVATION (GUESTHOUSE_RESERVATION_ID, FK_GUESTHOUSE_ROOM_ID, FK_RESERVATION_ID, GUEST_COUNT) VALUES ('GHR008',	'19',	450114,	2)
INTO BAGUESTHOUSE_RESERVATION (GUESTHOUSE_RESERVATION_ID, FK_GUESTHOUSE_ROOM_ID, FK_RESERVATION_ID, GUEST_COUNT) VALUES ('GHR009',	'12',	450115,	2)
INTO BAGUESTHOUSE_RESERVATION (GUESTHOUSE_RESERVATION_ID, FK_GUESTHOUSE_ROOM_ID, FK_RESERVATION_ID, GUEST_COUNT) VALUES ('GHR010',	'68',	450117,	2)
INTO BAGUESTHOUSE_RESERVATION (GUESTHOUSE_RESERVATION_ID, FK_GUESTHOUSE_ROOM_ID, FK_RESERVATION_ID, GUEST_COUNT) VALUES ('GHR011',	'55',	450118,	2)
INTO BAGUESTHOUSE_RESERVATION (GUESTHOUSE_RESERVATION_ID, FK_GUESTHOUSE_ROOM_ID, FK_RESERVATION_ID, GUEST_COUNT) VALUES ('GHR012',	'69',	450119,	2)
SELECT * FROM DUAL;


INSERT ALL
INTO BASTORE_BUSINESS_TYPE (STORE_BUSINESS_TYPE_ID, STORE_BUSINESS_TYPE_NAME, STORE_BUSINESS_TYPE_DESCRIPT) VALUES (1,	'Bookshop',	'A book shop')
INTO BASTORE_BUSINESS_TYPE (STORE_BUSINESS_TYPE_ID, STORE_BUSINESS_TYPE_NAME, STORE_BUSINESS_TYPE_DESCRIPT) VALUES (2,	'GiftShop',	'A gift shop')
INTO BASTORE_BUSINESS_TYPE (STORE_BUSINESS_TYPE_ID, STORE_BUSINESS_TYPE_NAME, STORE_BUSINESS_TYPE_DESCRIPT) VALUES (3,	'Produce Shop',	'A produce stand')
INTO BASTORE_BUSINESS_TYPE (STORE_BUSINESS_TYPE_ID, STORE_BUSINESS_TYPE_NAME, STORE_BUSINESS_TYPE_DESCRIPT) VALUES (4,	'Restaurant',	'A restaurant')
SELECT * FROM DUAL;

-- STORE_ENTITY
INSERT ALL 
INTO BASTORE_ENTITY (STORE_ID, FK_SCHEDULE_ID, STORE_NAME, FK_STORE_BUSINESS_TYPE_ID) VALUES ('B1',	20190506,	'Bookies',	1)
INTO BASTORE_ENTITY (STORE_ID, FK_SCHEDULE_ID, STORE_NAME, FK_STORE_BUSINESS_TYPE_ID) VALUES ('G1',	20190507,	'Gifties',	2)
INTO BASTORE_ENTITY (STORE_ID, FK_SCHEDULE_ID, STORE_NAME, FK_STORE_BUSINESS_TYPE_ID) VALUES ('P1',	20190508,	'Producies',	3)
INTO BASTORE_ENTITY (STORE_ID, FK_SCHEDULE_ID, STORE_NAME, FK_STORE_BUSINESS_TYPE_ID) VALUES ('E1',	20190509,	'Eateries',	4)
SELECT * FROM DUAL;

-- PAYROLL
INSERT ALL 
INTO BAPAYROLL (PAYROLL_ID, FK_STORE_ID, PAYPERIOD_START_DATE, PAYPERIOD_END_DATE) VALUES (9000,	'B1',	TO_DATE('6-1-19', 'MM-DD-YY'),	TO_DATE('6-15-19', 'MM-DD-YY'))
INTO BAPAYROLL (PAYROLL_ID, FK_STORE_ID, PAYPERIOD_START_DATE, PAYPERIOD_END_DATE) VALUES (9001,	'G1',	TO_DATE('6-1-19', 'MM-DD-YY'),	TO_DATE('6-15-19', 'MM-DD-YY'))
INTO BAPAYROLL (PAYROLL_ID, FK_STORE_ID, PAYPERIOD_START_DATE, PAYPERIOD_END_DATE) VALUES (9002,	'P1',	TO_DATE('6-1-19', 'MM-DD-YY'),	TO_DATE('6-15-19', 'MM-DD-YY'))
INTO BAPAYROLL (PAYROLL_ID, FK_STORE_ID, PAYPERIOD_START_DATE, PAYPERIOD_END_DATE) VALUES (9003,	'E1',	TO_DATE('6-1-19', 'MM-DD-YY'),	TO_DATE('6-15-19', 'MM-DD-YY'))
SELECT * FROM DUAL;

-- PAYCHECK
INSERT ALL 
INTO BAPAYCHECK (PAYCHECK_ID, FK_EMPLOYEE_ID, FK_PAYROLL_ID, HOURS_WORKED, PAY_RATE) VALUES (250025,	'L100',	9000,	37.5,	15.00)
INTO BAPAYCHECK (PAYCHECK_ID, FK_EMPLOYEE_ID, FK_PAYROLL_ID, HOURS_WORKED, PAY_RATE) VALUES (250026,	'L101',	9001,	37.5,	15.00)
INTO BAPAYCHECK (PAYCHECK_ID, FK_EMPLOYEE_ID, FK_PAYROLL_ID, HOURS_WORKED, PAY_RATE) VALUES (250027,	'L102',	9002,	37.5,	15.00)
INTO BAPAYCHECK (PAYCHECK_ID, FK_EMPLOYEE_ID, FK_PAYROLL_ID, HOURS_WORKED, PAY_RATE) VALUES (250028,	'L103',	9003,	37.5,	15.00)
INTO BAPAYCHECK (PAYCHECK_ID, FK_EMPLOYEE_ID, FK_PAYROLL_ID, HOURS_WORKED, PAY_RATE) VALUES (250029,	'L104',	9000,	37.5,	15.00)
INTO BAPAYCHECK (PAYCHECK_ID, FK_EMPLOYEE_ID, FK_PAYROLL_ID, HOURS_WORKED, PAY_RATE) VALUES (250030,	'L105',	9001,	37.5,	15.00)
INTO BAPAYCHECK (PAYCHECK_ID, FK_EMPLOYEE_ID, FK_PAYROLL_ID, HOURS_WORKED, PAY_RATE) VALUES (250031,	'L106',	9002,	37.5,	15.00)
INTO BAPAYCHECK (PAYCHECK_ID, FK_EMPLOYEE_ID, FK_PAYROLL_ID, HOURS_WORKED, PAY_RATE) VALUES (250032,	'L107',	9003,	37.5,	15.00)
SELECT * FROM DUAL;

-- RESTUARANT_RESERVATIONS
INSERT ALL 
INTO BARESTAURANT_RESERVATION (RESTAURANT_RESERVATION_ID, FK_STORE_ID, FK_RESERVATION_ID, NUM_OF_GUESTS) VALUES ('RR1001',	'E1',	450106,	2)
INTO BARESTAURANT_RESERVATION (RESTAURANT_RESERVATION_ID, FK_STORE_ID, FK_RESERVATION_ID, NUM_OF_GUESTS) VALUES ('RR1002',	'E1',	450107,	2)
INTO BARESTAURANT_RESERVATION (RESTAURANT_RESERVATION_ID, FK_STORE_ID, FK_RESERVATION_ID, NUM_OF_GUESTS) VALUES ('RR1003',	'E1',	450112,	2)
INTO BARESTAURANT_RESERVATION (RESTAURANT_RESERVATION_ID, FK_STORE_ID, FK_RESERVATION_ID, NUM_OF_GUESTS) VALUES ('RR1004',	'E1',	450116,	2)
SELECT * FROM DUAL;

-- STORE_INVENTORY
INSERT ALL
INTO BASTORE_INVENTORY (STORE_INVENTORY_ID, FK_STORE_ID, DATE_RECEIVED, SHIPMENT_ORDER) VALUES ('SI-B001',	'B1',	TO_DATE('6-3-19', 'MM-DD-YY'),	102938)
INTO BASTORE_INVENTORY (STORE_INVENTORY_ID, FK_STORE_ID, DATE_RECEIVED, SHIPMENT_ORDER) VALUES ('SI-G001',	'G1',	TO_DATE('6-6-19', 'MM-DD-YY'),	102939)
INTO BASTORE_INVENTORY (STORE_INVENTORY_ID, FK_STORE_ID, DATE_RECEIVED, SHIPMENT_ORDER) VALUES ('SI-P001',	'P1',	TO_DATE('6-10-19', 'MM-DD-YY'),	102940)
INTO BASTORE_INVENTORY (STORE_INVENTORY_ID, FK_STORE_ID, DATE_RECEIVED, SHIPMENT_ORDER) VALUES ('SI-E001',	'E1',	TO_DATE('6-13-19', 'MM-DD-YY'),	102941)
INTO BASTORE_INVENTORY (STORE_INVENTORY_ID, FK_STORE_ID, DATE_RECEIVED, SHIPMENT_ORDER) VALUES ('SI-G002',	'G1',	TO_DATE('6-13-19', 'MM-DD-YY'),	102941)
SELECT * FROM DUAL;

-- PRODUCT_TYPE
INSERT ALL
INTO BAPRODUCT_TYPE (PRODUCT_TYPE_ID, PRODUCT_TYPE_NAME, PRODUCT_TYPE_DESCRIPTION) VALUES ('B',	'BOOK',	'BookshopItem')
INTO BAPRODUCT_TYPE (PRODUCT_TYPE_ID, PRODUCT_TYPE_NAME, PRODUCT_TYPE_DESCRIPTION) VALUES ('G',	'GIFT',	'GiftshopItem')
INTO BAPRODUCT_TYPE (PRODUCT_TYPE_ID, PRODUCT_TYPE_NAME, PRODUCT_TYPE_DESCRIPTION) VALUES ('P',	'PROD',	'ProduceItem')
INTO BAPRODUCT_TYPE (PRODUCT_TYPE_ID, PRODUCT_TYPE_NAME, PRODUCT_TYPE_DESCRIPTION) VALUES ('R',	'REST',	'RestaurantItem')
SELECT * FROM DUAL;

-- PRODUCT
INSERT ALL
INTO BAPRODUCT (PRODUCT_ID, FK_PRODUCT_TYPE_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_PRICE, PRODUCT_COST) VALUES ('SKU1000',	'B',	'Bible',	'The official version',	10.00,	1.00)
INTO BAPRODUCT (PRODUCT_ID, FK_PRODUCT_TYPE_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_PRICE, PRODUCT_COST) VALUES ('SKU1001',	'G',	'Cinnamon Candle',	'Smells nice',	5.00,	1.00)
INTO BAPRODUCT (PRODUCT_ID, FK_PRODUCT_TYPE_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_PRICE, PRODUCT_COST) VALUES ('SKU1002',	'P',	'Red Apple',	'Tasty and red',	2.00,	0.25)
INTO BAPRODUCT (PRODUCT_ID, FK_PRODUCT_TYPE_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_PRICE, PRODUCT_COST) VALUES ('SKU1003',	'R',	'Fish Sticks',	'Fishy',	15.00,	2.00)
INTO BAPRODUCT (PRODUCT_ID, FK_PRODUCT_TYPE_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_PRICE, PRODUCT_COST) VALUES ('SKU1004',	'R',	'Sandwich',	'Turkey and Jack',	15.00,	2.00)
INTO BAPRODUCT (PRODUCT_ID, FK_PRODUCT_TYPE_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_PRICE, PRODUCT_COST) VALUES ('SKU1005',	'R',	'Black Tea',	'Tea',	4.00,	0.25)
INTO BAPRODUCT (PRODUCT_ID, FK_PRODUCT_TYPE_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_PRICE, PRODUCT_COST) VALUES ('SKU1006',	'R',	'Lemon Bar',	'Lemony',	3.00,	0.75)
INTO BAPRODUCT (PRODUCT_ID, FK_PRODUCT_TYPE_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_PRICE, PRODUCT_COST) VALUES ('SKU1007',	'B',	'Women of the Bible',	'The untold history',	10.00,	1.00)
INTO BAPRODUCT (PRODUCT_ID, FK_PRODUCT_TYPE_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_PRICE, PRODUCT_COST) VALUES ('SKU1008',	'G',	'Vanilla Candle',	'Smells like vanilla',	5.00,	1.00)
INTO BAPRODUCT (PRODUCT_ID, FK_PRODUCT_TYPE_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_PRICE, PRODUCT_COST) VALUES ('SKU1009',	'P',	'Italian Herbs',	'Sage, Rosemary, and Thyme',	6.00,	1.00)
INTO BAPRODUCT (PRODUCT_ID, FK_PRODUCT_TYPE_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_PRICE, PRODUCT_COST) VALUES ('SKU1010',	'B',	'Christianity and You',	'A book by the Abbott',	8.00,	1.00)
INTO BAPRODUCT (PRODUCT_ID, FK_PRODUCT_TYPE_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_PRICE, PRODUCT_COST) VALUES ('SKU1011',	'G',	'Large Cinnamon Candle',	'There’s more cinnamon and it is bigger',	10.00,	1.50)
INTO BAPRODUCT (PRODUCT_ID, FK_PRODUCT_TYPE_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_PRICE, PRODUCT_COST) VALUES ('SKU1012',	'P',	'Sugar Beets',	'Sweet beets',	2.00,	0.25)
INTO BAPRODUCT (PRODUCT_ID, FK_PRODUCT_TYPE_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_PRICE, PRODUCT_COST) VALUES ('SKU1013',	'R',	'Chicken Dinner',	'Chickeny',	15.00,	2.00)
SELECT * FROM DUAL;

-- BAVENDOR
INSERT ALL
INTO BAVENDOR (VENDOR_ID, VENDOR_NAME) VALUES ('V1067',	'Booker Brothers')
INTO BAVENDOR (VENDOR_ID, VENDOR_NAME) VALUES ('V1068',	'Gregory’s Gifts')
INTO BAVENDOR (VENDOR_ID, VENDOR_NAME) VALUES ('V1069',	'Poppas Pickers')
INTO BAVENDOR (VENDOR_ID, VENDOR_NAME) VALUES ('V1070',	'Salem Sisters')
INTO BAVENDOR (VENDOR_ID, VENDOR_NAME) VALUES ('V1071',	'Snicket’s Lemons')
INTO BAVENDOR (VENDOR_ID, VENDOR_NAME) VALUES ('V1072',	'Moor Candles')
INTO BAVENDOR (VENDOR_ID, VENDOR_NAME) VALUES ('V1073',	'Dowager’s Delights')
INTO BAVENDOR (VENDOR_ID, VENDOR_NAME) VALUES ('V1074',	'Finnish Fishes')
INTO BAVENDOR (VENDOR_ID, VENDOR_NAME) VALUES ('V1075',	'Cannery Cooks')
SELECT * FROM DUAL;


-- STORE INVENTORY LINE ITEM
INSERT ALL 
INTO BASTORE_INVENTORY_LINEITEM (STORE_INVENTORY_LINEITEM_ID, FK_PRODUCTID, FK_STORE_INVENTORY_ID, FK_VENDOR_ID, QUANTITY) VALUES (10000,	'SKU1000',	'SI-B001',	'V1067',	10)
INTO BASTORE_INVENTORY_LINEITEM (STORE_INVENTORY_LINEITEM_ID, FK_PRODUCTID, FK_STORE_INVENTORY_ID, FK_VENDOR_ID, QUANTITY) VALUES (10001,	'SKU1001',	'SI-G001',	'V1072',	15)
INTO BASTORE_INVENTORY_LINEITEM (STORE_INVENTORY_LINEITEM_ID, FK_PRODUCTID, FK_STORE_INVENTORY_ID, FK_VENDOR_ID, QUANTITY) VALUES (10002,	'SKU1002',	'SI-P001',	'V1069',	12)
INTO BASTORE_INVENTORY_LINEITEM (STORE_INVENTORY_LINEITEM_ID, FK_PRODUCTID, FK_STORE_INVENTORY_ID, FK_VENDOR_ID, QUANTITY) VALUES (10003,	'SKU1003',	'SI-E001',	'V1074',	7)
INTO BASTORE_INVENTORY_LINEITEM (STORE_INVENTORY_LINEITEM_ID, FK_PRODUCTID, FK_STORE_INVENTORY_ID, FK_VENDOR_ID, QUANTITY) VALUES (10004,	'SKU1004',	'SI-E001',	'V1070',	9)
INTO BASTORE_INVENTORY_LINEITEM (STORE_INVENTORY_LINEITEM_ID, FK_PRODUCTID, FK_STORE_INVENTORY_ID, FK_VENDOR_ID, QUANTITY) VALUES (10005,	'SKU1005',	'SI-E001',	'V1073',	50)
INTO BASTORE_INVENTORY_LINEITEM (STORE_INVENTORY_LINEITEM_ID, FK_PRODUCTID, FK_STORE_INVENTORY_ID, FK_VENDOR_ID, QUANTITY) VALUES (10006,	'SKU1006',	'SI-E001',	'V1071',	35)
INTO BASTORE_INVENTORY_LINEITEM (STORE_INVENTORY_LINEITEM_ID, FK_PRODUCTID, FK_STORE_INVENTORY_ID, FK_VENDOR_ID, QUANTITY) VALUES (10007,	'SKU1007',	'SI-B001',	'V1070',	13)
INTO BASTORE_INVENTORY_LINEITEM (STORE_INVENTORY_LINEITEM_ID, FK_PRODUCTID, FK_STORE_INVENTORY_ID, FK_VENDOR_ID, QUANTITY) VALUES (10008,	'SKU1008',	'SI-G001',	'V1068',	20)
INTO BASTORE_INVENTORY_LINEITEM (STORE_INVENTORY_LINEITEM_ID, FK_PRODUCTID, FK_STORE_INVENTORY_ID, FK_VENDOR_ID, QUANTITY) VALUES (10009,	'SKU1008',	'SI-P001',	'V1069',	10)
INTO BASTORE_INVENTORY_LINEITEM (STORE_INVENTORY_LINEITEM_ID, FK_PRODUCTID, FK_STORE_INVENTORY_ID, FK_VENDOR_ID, QUANTITY) VALUES (10010,	'SKU1010',	'SI-B001',	'V1067',	4)
INTO BASTORE_INVENTORY_LINEITEM (STORE_INVENTORY_LINEITEM_ID, FK_PRODUCTID, FK_STORE_INVENTORY_ID, FK_VENDOR_ID, QUANTITY) VALUES (10011,	'SKU1011',	'SI-G001',	'V1070',	17)
INTO BASTORE_INVENTORY_LINEITEM (STORE_INVENTORY_LINEITEM_ID, FK_PRODUCTID, FK_STORE_INVENTORY_ID, FK_VENDOR_ID, QUANTITY) VALUES (10012,	'SKU1012',	'SI-P001',	'V1069',	23)
INTO BASTORE_INVENTORY_LINEITEM (STORE_INVENTORY_LINEITEM_ID, FK_PRODUCTID, FK_STORE_INVENTORY_ID, FK_VENDOR_ID, QUANTITY) VALUES (10013,	'SKU1013',	'SI-E001',	'V1075',	25)
SELECT * FROM DUAL;


-- TRANSACTION LINE ITEM
INSERT ALL 
INTO BATRANSACTION_LINE_ITEM (TRANSACTION_LINE_ITEM_ID, FK_PRODUCT_ID, FK_SALE_TRANSACTION_ID, QUANTITY, PRICE) VALUES (8001,	'SKU1002',	3331005,	2,	2.00)
INTO BATRANSACTION_LINE_ITEM (TRANSACTION_LINE_ITEM_ID, FK_PRODUCT_ID, FK_SALE_TRANSACTION_ID, QUANTITY, PRICE) VALUES (8002,	'SKU1004',	3331023,	1,	15.00)
INTO BATRANSACTION_LINE_ITEM (TRANSACTION_LINE_ITEM_ID, FK_PRODUCT_ID, FK_SALE_TRANSACTION_ID, QUANTITY, PRICE) VALUES (8003,	'SKU1006',	3331016,	3,	3.00)
INTO BATRANSACTION_LINE_ITEM (TRANSACTION_LINE_ITEM_ID, FK_PRODUCT_ID, FK_SALE_TRANSACTION_ID, QUANTITY, PRICE) VALUES (8004,	'SKU1013',	3331015,	1,	15.00)
INTO BATRANSACTION_LINE_ITEM (TRANSACTION_LINE_ITEM_ID, FK_PRODUCT_ID, FK_SALE_TRANSACTION_ID, QUANTITY, PRICE) VALUES (8005,	'SKU1001',	3331004,	8,	5.00)
INTO BATRANSACTION_LINE_ITEM (TRANSACTION_LINE_ITEM_ID, FK_PRODUCT_ID, FK_SALE_TRANSACTION_ID, QUANTITY, PRICE) VALUES (8006,	'SKU1004',	3331010,	2,	15.00)
INTO BATRANSACTION_LINE_ITEM (TRANSACTION_LINE_ITEM_ID, FK_PRODUCT_ID, FK_SALE_TRANSACTION_ID, QUANTITY, PRICE) VALUES (8007,	'SKU1003',	3331010,	1,	15.00)
INTO BATRANSACTION_LINE_ITEM (TRANSACTION_LINE_ITEM_ID, FK_PRODUCT_ID, FK_SALE_TRANSACTION_ID, QUANTITY, PRICE) VALUES (8008,	'SKU1013',	3331010,	1,	15.00)
SELECT * FROM DUAL;




COMMIT;




