Drop table BACustomer_Address_Type cascade constraints;
Drop table BACustomer cascade constraints;
Drop table BACustomer_Address cascade constraints;
Drop table BASale_Transaction cascade constraints;
Drop table BAReservation cascade constraints;
Drop table BASchedule cascade constraints;
Drop table BAEmployee_Type cascade constraints;
Drop table BAEmployee cascade constraints;
Drop table BAShift cascade constraints;
Drop table BAGuestHouse cascade constraints;
Drop table BAGuestHouse_Room cascade constraints;
Drop table BAGuestHouse_Reservation cascade constraints;
Drop table BAStore_Business_Type cascade constraints;
Drop table BAStore_Entity cascade constraints;
Drop table BAPayroll cascade constraints;
Drop table BAPaycheck cascade constraints;
Drop table BARestaurant_Reservation cascade constraints;
Drop table BAStoreInventory cascade constraints;
Drop table BAProduct_Type cascade constraints;
Drop table BAProduct cascade constraints;
Drop table BAVendor cascade constraints;
Drop table BAStoreInventory_LineItem cascade constraints;
Drop table BATransaction_Line_Item cascade constraints;


/*
  Create the tables
*/


CREATE TABLE BACustomer_Address_Type (
  Address_Type_ID number(10) not null,
  Address_Type_Description varchar2(100) not null,
  PRIMARY KEY (Address_Type_ID)
);

CREATE TABLE BACustomer (
  Customer_ID varchar2(15) not null,
  First_Name varchar2(100) not null,
  Last_Name varchar2(100) not null,
  PRIMARY KEY (Customer_ID)
);

CREATE TABLE BACustomer_Address (
  Customer_Address_ID number(10) not null,
  Street_Address varchar2(100) not null,
  City varchar2(50) not null,
  State varchar2(50) not null,
  Zipcode varchar2(20) not null,
  FK_Customer_ID varchar2(15) not null,
  FK_Customer_Address_Type_ID number(10) not null,
  PRIMARY KEY (Customer_Address_ID),
  FOREIGN KEY (FK_Customer_ID) REFERENCES BACustomer (Customer_ID),
  FOREIGN KEY (FK_Customer_Address_Type_ID) REFERENCES BACustomer_Address_Type (Address_Type_ID)
);

CREATE TABLE BASale_Transaction (
  Sale_Transaction_ID number(10)  not null,
  FK_Customer_ID varchar2(15) not null,
  TransactionDate Date not null,
  Transaction_Amount number(8,2) not null,
  PRIMARY KEY (Sale_Transaction_ID),
  FOREIGN KEY (FK_Customer_ID) REFERENCES BACustomer (Customer_ID)
);

CREATE TABLE BAReservation (
  Reservation_ID number(10) not null,
  FK_Customer_ID varchar2(15)  not null,
  DateStart Date not null,
  DateEnd Date not null,
  Reservation_Price number(8,2) not null,
  PRIMARY KEY (Reservation_ID),
  FOREIGN KEY (FK_Customer_ID) REFERENCES BACustomer (Customer_ID)
);

CREATE TABLE BASchedule (
  Schedule_ID number(10) not null,
  StartDate Date not null,
  EndDate Date not null,
  PRIMARY KEY (Schedule_ID)
);

CREATE TABLE BAEmployee_Type (
  Employee_Type_ID number(10),
  Employee_Type_Name varchar2(100),
  Employee_Type_Description varchar2(200),
  PRIMARY KEY (Employee_Type_ID)
);

CREATE TABLE BAEmployee (
  Employee_ID varchar2(15) not null,
  FK_Employee_Type_ID  not null,
  PRIMARY KEY (Employee_ID),
  FOREIGN KEY (FK_Employee_Type_ID) REFERENCES BAEmployee_Type (Employee_Type_ID)
);

CREATE TABLE BAShift (
  Shift_ID number(10) not null,
  FK_Employee_ID varchar2(15) not null,
  FK_Schedule_ID number(10) not null,
  End_Time Date not null,
  Shift_Date Date not null,
  Start_Time Date not null,
  PRIMARY KEY (Shift_ID),
  FOREIGN KEY (FK_Employee_ID) REFERENCES BAEmployee (Employee_ID), 
  FOREIGN KEY (FK_Schedule_ID) REFERENCES BASchedule (Schedule_ID)
);

CREATE TABLE BAGuestHouse (
  GuestHouse_ID varchar(15) not null,
  Num_of_Room number(3) not null,
  Max_Occupancy number(3) not null,
  FK_Schedule_ID number(10) not null,
  GuestHouse_Name varchar2(100) not null,
  PRIMARY KEY (GuestHouse_ID), 
  FOREIGN KEY (FK_Schedule_ID) REFERENCES BASchedule (Schedule_ID)
);

CREATE TABLE BAGuestHouse_Room (
  GuestHouse_Room_ID varchar2(15) not null,
  FK_GuestHouse_ID varchar2(15) not null,
  Room_Name varchar2(50) not null,
  Room_Occupancy number(2) not null,
  Room_Price number(8,2) not null,
  PRIMARY KEY (GuestHouse_Room_ID),
  FOREIGN KEY (FK_GuestHouse_ID) REFERENCES BAGuestHouse (GuestHouse_ID)
);

CREATE TABLE BAGuestHouse_Reservation (
  GuestHouse_Reservation_ID varchar2(15) not null,
  FK_GuestHouse_Room_ID varchar2(15) not null,
  FK_Reservation_ID number(10) not null,
  Guest_Count number(2) not null,
  PRIMARY KEY (GuestHouse_Reservation_ID),
  FOREIGN KEY (FK_GuestHouse_Room_ID) REFERENCES BAGuestHouse_Room (GuestHouse_Room_ID),
  FOREIGN KEY (FK_Reservation_ID) REFERENCES BAReservation (Reservation_ID)
);

CREATE TABLE BAStore_Business_Type (
  Store_Business_Type_ID number(4) not null,
  Store_Business_Type_Name varchar2(100) not null,
  Store_Business_Type_Descript varchar2(200) not null,
  PRIMARY KEY (Store_Business_Type_ID)
);

CREATE TABLE BAStore_Entity (
  Store_ID varchar2(15) not null,
  FK_Schedule_ID number(10) not null,
  Store_Name varchar2(100) not null,
  FK_Store_Business_Type_ID number(4) not null,
  PRIMARY KEY (Store_ID),
  FOREIGN KEY (FK_Schedule_ID) REFERENCES BASchedule (Schedule_ID),
  FOREIGN KEY (FK_Store_Business_Type_ID) REFERENCES BAStore_Business_Type (Store_Business_Type_ID)
);

CREATE TABLE BAPayroll (
  Payroll_ID number(10) not null,
  FK_Store_ID varchar2(15) not null,
  PayPeriodStartDate Date not null,
  PayPeriodEndDate Date not null,
  PRIMARY KEY (Payroll_ID),
  FOREIGN KEY (FK_Store_ID) REFERENCES BAStore_Entity (Store_ID)
);

CREATE TABLE BAPaycheck (
  Paycheck_ID number(10) not null,
  FK_Employee_ID varchar2(15) not null,
  FK_Payroll_ID number(10) not null,
  Hours_Worked number(6,2) not null,
  Pay_Rate number(6,2) not null,
  PRIMARY KEY (Paycheck_ID),
  FOREIGN KEY (FK_Employee_ID) REFERENCES BAEmployee (Employee_ID),
  FOREIGN KEY (FK_Payroll_ID) REFERENCES BAPayroll (Payroll_ID)
);

CREATE TABLE BARestaurant_Reservation (
  Restaurant_Reservation_ID varchar(15) not null,
  FK_Store_ID varchar2(15) not null,
  FK_Reservation_ID number(10) not null,
  Num_of_Guests number(3) not null,
  PRIMARY KEY (Restaurant_Reservation_ID),
  FOREIGN KEY (FK_Store_ID) REFERENCES BAStore_Entity (Store_ID),
  FOREIGN KEY (FK_Reservation_ID) REFERENCES BAReservation (Reservation_ID)
);

CREATE TABLE BAStoreInventory (
  StoreInventory_ID varchar(15) not null,
  FK_Store_ID varchar(15) not null,
  DateReceived Date  not null,
  Shipment_Order varchar(20) not null,
  PRIMARY KEY (StoreInventory_ID),
  FOREIGN KEY (FK_Store_ID) REFERENCES BAStore_Entity (Store_ID)
);

CREATE TABLE BAProduct_Type (
  Product_Type_ID varchar2(15) not null,
  Product_Type_Name varchar2(100) not null,
  Product_Type_Description varchar2(300),
  PRIMARY KEY (Product_Type_ID)
);

CREATE TABLE BAProduct (
  Product_ID varchar2(15) not null,
  FK_Product_Type_ID varchar2(15) not null,
  Product_Name varchar2(100) not null,
  Product_Description varchar2(300),
  Product_Price number(8,2) not null,
  Product_Cost number(8,2) not null,
  PRIMARY KEY (Product_ID)
);

CREATE TABLE BAVendor (
  Vendor_ID varchar2(15) not null,
  VendorName varchar2(100) not null,
  PRIMARY KEY (Vendor_ID)
);

CREATE TABLE BAStoreInventory_LineItem (
  StoreInventory_LineItem_ID number(10) not null,
  FK_ProductID varchar2(15) not null,
  FK_StoreInventory_ID varchar2(15) not null,
  FK_Vendor_ID varchar2(15) not null,
  Quantity number(4) not null,
  PRIMARY KEY (StoreInventory_LineItem_ID),
  FOREIGN KEY (FK_ProductID) REFERENCES BAProduct (Product_ID),
  FOREIGN KEY (FK_StoreInventory_ID) REFERENCES BAStoreInventory (StoreInventory_ID),
  FOREIGN KEY (FK_Vendor_ID) REFERENCES BAVendor (Vendor_ID)
);

CREATE TABLE BATransaction_Line_Item (
  Transaction_Line_Item_ID number(10) not null,
  FK_Product_ID varchar2(15),
  FK_Sale_Transaction_ID number(10),
  Quantity number(4),
  Price number(8,2),
  PRIMARY KEY (Transaction_Line_Item_ID),
  FOREIGN KEY (FK_Product_ID) REFERENCES BAProduct (Product_ID),
  FOREIGN KEY (FK_Sale_Transaction_ID) REFERENCES BASale_Transaction (Sale_Transaction_ID)
);



--------------------------------------INSERT

-- ADDRESS_TYPE
INSERT ALL
INTO BACUSTOMER_ADDRESS_TYPE (ADDRESS_TYPE_ID, ADDRESS_TYPE_DESCRIPTION) VALUES (1,	'Home')
INTO BACUSTOMER_ADDRESS_TYPE (ADDRESS_TYPE_ID, ADDRESS_TYPE_DESCRIPTION) VALUES (2,	'Business')
INTO BACUSTOMER_ADDRESS_TYPE (ADDRESS_TYPE_ID, ADDRESS_TYPE_DESCRIPTION) VALUES (3,	'Shipping')
INTO BACUSTOMER_ADDRESS_TYPE (ADDRESS_TYPE_ID, ADDRESS_TYPE_DESCRIPTION) VALUES (4,	'Postal Box')
SELECT * FROM DUAL;

-- CUSTOMER
INSERT ALL
INTO BACUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME) VALUES ('C1004',	'Angela',	'Merkel')
INTO BACUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME) VALUES ('C1005',	'Tissaia',	'deVries')
INTO BACUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME) VALUES ('C1006',	'Ada',	'Lovelace')
INTO BACUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME) VALUES ('C1007',	'Arya',	'Stark')
INTO BACUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME) VALUES ('C1008',	'Yennefer',	'Vengerberg')
INTO BACUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME) VALUES ('C1009',	'Diana',	'Prince')
INTO BACUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME) VALUES ('C1010',	'Kara',	'Zor-el')
INTO BACUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME) VALUES ('C1011',	'Carol',	'Danvers')
INTO BACUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME) VALUES ('C1012',	'Barbara',	'Kingsolver')
INTO BACUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME) VALUES ('C1013',	'Taelia',	'Fordragon')
INTO BACUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME) VALUES ('C1014',	'Jaina',	'Proudmoore')
SELECT * FROM DUAL;

-- CUSTOMER_ADDRESS
INSERT ALL
INTO BACUSTOMER_ADDRESS (CUSTOMER_ADDRESS_ID, STREET_ADDRESS, CITY, STATE, ZIPCODE, FK_CUSTOMER_ID, FK_CUSTOMER_ADDRESS_TYPE_ID) VALUES (2601004,	'Prenzlauer Allee 6',	'Templin',	'Brandenburg',	'17268',	'C1004',	2)
INTO BACUSTOMER_ADDRESS (CUSTOMER_ADDRESS_ID, STREET_ADDRESS, CITY, STATE, ZIPCODE, FK_CUSTOMER_ID, FK_CUSTOMER_ADDRESS_TYPE_ID) VALUES (2601005,	'13-1 Waterford Place',	'Aretuza',	'Thanedd',	'1267',	'C1005',	2)
INTO BACUSTOMER_ADDRESS (CUSTOMER_ADDRESS_ID, STREET_ADDRESS, CITY, STATE, ZIPCODE, FK_CUSTOMER_ID, FK_CUSTOMER_ADDRESS_TYPE_ID) VALUES (2601006,	'Woking 6NL',	'Ockham',	'Surrey',	'GU23',	'C1006',	1)
INTO BACUSTOMER_ADDRESS (CUSTOMER_ADDRESS_ID, STREET_ADDRESS, CITY, STATE, ZIPCODE, FK_CUSTOMER_ID, FK_CUSTOMER_ADDRESS_TYPE_ID) VALUES (2601007,	'165 E 7th Ave',	'Temple',	'Bravos',	'23TEMP',	'C1007',	4)
INTO BACUSTOMER_ADDRESS (CUSTOMER_ADDRESS_ID, STREET_ADDRESS, CITY, STATE, ZIPCODE, FK_CUSTOMER_ID, FK_CUSTOMER_ADDRESS_TYPE_ID) VALUES (2601008,	'13-3 Waterford Place',	'Aretuza',	'Thanedd',	'1267',	'C1008',	3)
INTO BACUSTOMER_ADDRESS (CUSTOMER_ADDRESS_ID, STREET_ADDRESS, CITY, STATE, ZIPCODE, FK_CUSTOMER_ID, FK_CUSTOMER_ADDRESS_TYPE_ID) VALUES (2601009,	'Royal Quarters #1',	'Paradise Island',	'Themyscira',	'630 88',	'C1009',	1)
INTO BACUSTOMER_ADDRESS (CUSTOMER_ADDRESS_ID, STREET_ADDRESS, CITY, STATE, ZIPCODE, FK_CUSTOMER_ID, FK_CUSTOMER_ADDRESS_TYPE_ID) VALUES (2601010,	'1961 Eastern Rim',	'Argo City',	'Krypton',	'279123',	'C1010',	1)
INTO BACUSTOMER_ADDRESS (CUSTOMER_ADDRESS_ID, STREET_ADDRESS, CITY, STATE, ZIPCODE, FK_CUSTOMER_ID, FK_CUSTOMER_ADDRESS_TYPE_ID) VALUES (2601011,	'303 Hinkle Lake Road',	'Boston',	'Massachusetts',	'02114',	'C1011',	3)
INTO BACUSTOMER_ADDRESS (CUSTOMER_ADDRESS_ID, STREET_ADDRESS, CITY, STATE, ZIPCODE, FK_CUSTOMER_ID, FK_CUSTOMER_ADDRESS_TYPE_ID) VALUES (2601012,	'719 Main St',	'Apalachin',	'New York',	'13732',	'C1012',	1)
INTO BACUSTOMER_ADDRESS (CUSTOMER_ADDRESS_ID, STREET_ADDRESS, CITY, STATE, ZIPCODE, FK_CUSTOMER_ID, FK_CUSTOMER_ADDRESS_TYPE_ID) VALUES (2601013,	'478 Military Ward Dr',	'Boralus',	'Kul Tiras',	'90004',	'C1013',	1)
INTO BACUSTOMER_ADDRESS (CUSTOMER_ADDRESS_ID, STREET_ADDRESS, CITY, STATE, ZIPCODE, FK_CUSTOMER_ID, FK_CUSTOMER_ADDRESS_TYPE_ID) VALUES (2601014,	'1000 Capital Way',	'Boralus',	'Kul Tiras',	'90005',	'C1014',	3)
SELECT * FROM DUAL;

-- SALE_TRANSACTION
INSERT ALL
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTIONDATE, TRANSACTION_AMOUNT) VALUES (3331004,	'C1004',	TO_DATE('6-1-19', 'MM-DD-YY'),	40.00)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTIONDATE, TRANSACTION_AMOUNT) VALUES (3331005,	'C1005',	TO_DATE('6-4-19', 'MM-DD-YY'),	10.50)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTIONDATE, TRANSACTION_AMOUNT) VALUES (3331006,	'C1006',	TO_DATE('6-7-19', 'MM-DD-YY'),	37.89)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTIONDATE, TRANSACTION_AMOUNT) VALUES (3331007,	'C1007',  TO_DATE('6-11-19', 'MM-DD-YY'),	123.54)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTIONDATE, TRANSACTION_AMOUNT) VALUES (3331008,	'C1008',	TO_DATE('6-15-19', 'MM-DD-YY'),	14.56)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTIONDATE, TRANSACTION_AMOUNT) VALUES (3331009,	'C1009',	TO_DATE('6-21-19', 'MM-DD-YY'),	87.13)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTIONDATE, TRANSACTION_AMOUNT) VALUES (3331010,	'C1010',	TO_DATE('6-28-19', 'MM-DD-YY'),	63.99)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTIONDATE, TRANSACTION_AMOUNT) VALUES (3331011,	'C1011',	TO_DATE('7-1-19', 'MM-DD-YY'),	82.09)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTIONDATE, TRANSACTION_AMOUNT) VALUES (3331012,	'C1012',	TO_DATE('7-2-19', 'MM-DD-YY'),	13.05)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTIONDATE, TRANSACTION_AMOUNT) VALUES (3331013,	'C1013',	TO_DATE('7-5-19', 'MM-DD-YY'),	45.45)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTIONDATE, TRANSACTION_AMOUNT) VALUES (3331014,	'C1014',	TO_DATE('7-8-19', 'MM-DD-YY'),	55.52)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTIONDATE, TRANSACTION_AMOUNT) VALUES (3331015,	'C1004',	TO_DATE('7-9-12', 'MM-DD-YY'),	23.23)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTIONDATE, TRANSACTION_AMOUNT) VALUES (3331016,	'C1005',	TO_DATE('7-13-19', 'MM-DD-YY'),	9.67)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTIONDATE, TRANSACTION_AMOUNT) VALUES (3331017,	'C1006',	TO_DATE('7-17-19', 'MM-DD-YY'),	33.87)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTIONDATE, TRANSACTION_AMOUNT) VALUES (3331018,	'C1007',	TO_DATE('7-20-19', 'MM-DD-YY'),	90.05)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTIONDATE, TRANSACTION_AMOUNT) VALUES (3331019,	'C1008',	TO_DATE('7-27-19', 'MM-DD-YY'),	72.89)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTIONDATE, TRANSACTION_AMOUNT) VALUES (3331020,	'C1009',	TO_DATE('7-31-19', 'MM-DD-YY'),	145.65)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTIONDATE, TRANSACTION_AMOUNT) VALUES (3331021,	'C1010',	TO_DATE('8-1-19', 'MM-DD-YY'),	67.67)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTIONDATE, TRANSACTION_AMOUNT) VALUES (3331022,	'C1011',	TO_DATE('8-3-19', 'MM-DD-YY'),	65.23)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTIONDATE, TRANSACTION_AMOUNT) VALUES (3331023,	'C1012',	TO_DATE('8-5-19', 'MM-DD-YY'),	15.00)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTIONDATE, TRANSACTION_AMOUNT) VALUES (3331024,	'C1013',	TO_DATE('8-7-19', 'MM-DD-YY'),	13.25)
INTO BASALE_TRANSACTION (SALE_TRANSACTION_ID, FK_CUSTOMER_ID, TRANSACTIONDATE, TRANSACTION_AMOUNT) VALUES (3331025,	'C1014',	TO_DATE('8-8-19', 'MM-DD-YY'),	55.45)
SELECT * FROM DUAL;

-- RESERVATION
INSERT ALL 
INTO BARESERVATION (RESERVATION_ID, FK_CUSTOMER_ID, DATESTART, DATEEND, RESERVATION_PRICE) VALUES (450104, 'C1014',	TO_DATE('6-1-19', 'MM-DD-YY'),	TO_DATE('6-14-19', 'MM-DD-YY'),	840)
INTO BARESERVATION (RESERVATION_ID, FK_CUSTOMER_ID, DATESTART, DATEEND, RESERVATION_PRICE) VALUES (450105, 'C1012',	TO_DATE('6-2-19', 'MM-DD-YY'),	TO_DATE('6-7-19', 'MM-DD-YY'),	360)
INTO BARESERVATION (RESERVATION_ID, FK_CUSTOMER_ID, DATESTART, DATEEND, RESERVATION_PRICE) VALUES (450106,	'C1010',	TO_DATE('6-4-19', 'MM-DD-YY'), TO_DATE('6-4-19', 'MM-DD-YY'),	0)
INTO BARESERVATION (RESERVATION_ID, FK_CUSTOMER_ID, DATESTART, DATEEND, RESERVATION_PRICE) VALUES (450107,	'C1008',	TO_DATE('6-4-19', 'MM-DD-YY'),	TO_DATE('6-4-19', 'MM-DD-YY'),	0)
INTO BARESERVATION (RESERVATION_ID, FK_CUSTOMER_ID, DATESTART, DATEEND, RESERVATION_PRICE) VALUES (450108,	'C1006',	TO_DATE('6-4-19', 'MM-DD-YY'),	TO_DATE('6-10-19', 'MM-DD-YY'),	420)
INTO BARESERVATION (RESERVATION_ID, FK_CUSTOMER_ID, DATESTART, DATEEND, RESERVATION_PRICE) VALUES (450109,	'C1004',	TO_DATE('6-5-19', 'MM-DD-YY'),	TO_DATE('6-7-19', 'MM-DD-YY'),	180)
INTO BARESERVATION (RESERVATION_ID, FK_CUSTOMER_ID, DATESTART, DATEEND, RESERVATION_PRICE) VALUES (450110,	'C1013', TO_DATE('6-6-19', 'MM-DD-YY'),	TO_DATE('6-8-19', 'MM-DD-YY'),	180)
INTO BARESERVATION (RESERVATION_ID, FK_CUSTOMER_ID, DATESTART, DATEEND, RESERVATION_PRICE) VALUES (450111,	'C1011',	TO_DATE('6-10-19', 'MM-DD-YY'),	TO_DATE('6-12-19', 'MM-DD-YY'),	180)
INTO BARESERVATION (RESERVATION_ID, FK_CUSTOMER_ID, DATESTART, DATEEND, RESERVATION_PRICE) VALUES (450112,	'C1009',	TO_DATE('6-15-19', 'MM-DD-YY'),	TO_DATE('6-15-19', 'MM-DD-YY'),	0)
INTO BARESERVATION (RESERVATION_ID, FK_CUSTOMER_ID, DATESTART, DATEEND, RESERVATION_PRICE) VALUES (450113,	'C1007',	TO_DATE('6-15-19', 'MM-DD-YY'),	TO_DATE('6-25-19', 'MM-DD-YY'),	660)
INTO BARESERVATION (RESERVATION_ID, FK_CUSTOMER_ID, DATESTART, DATEEND, RESERVATION_PRICE) VALUES (450114,	'C1005',	TO_DATE('6-19-19', 'MM-DD-YY'),	TO_DATE('6-21-19', 'MM-DD-YY'),	180)
INTO BARESERVATION (RESERVATION_ID, FK_CUSTOMER_ID, DATESTART, DATEEND, RESERVATION_PRICE) VALUES (450115,	'C1011',	TO_DATE('6-20-19', 'MM-DD-YY'), TO_DATE('6-30-19', 'MM-DD-YY'),	660)
INTO BARESERVATION (RESERVATION_ID, FK_CUSTOMER_ID, DATESTART, DATEEND, RESERVATION_PRICE) VALUES (450116,	'C1008',	TO_DATE('7-3-19', 'MM-DD-YY'),	TO_DATE('7-3-19', 'MM-DD-YY'),	0)
INTO BARESERVATION (RESERVATION_ID, FK_CUSTOMER_ID, DATESTART, DATEEND, RESERVATION_PRICE) VALUES (450117,	'C1014',	TO_DATE('7-21-19', 'MM-DD-YY'),	TO_DATE('7-24-19', 'MM-DD-YY'),	240)
INTO BARESERVATION (RESERVATION_ID, FK_CUSTOMER_ID, DATESTART, DATEEND, RESERVATION_PRICE) VALUES (450118,	'C1014',	TO_DATE('7-28-19', 'MM-DD-YY'),	TO_DATE('7-29-19', 'MM-DD-YY'),	120)
INTO BARESERVATION (RESERVATION_ID, FK_CUSTOMER_ID, DATESTART, DATEEND, RESERVATION_PRICE) VALUES (450119,	'C1009',	TO_DATE('8-15-19', 'MM-DD-YY'),	TO_DATE('8-30-19', 'MM-DD-YY'),	960)
SELECT * FROM DUAL;

-- SCHEDULE
INSERT ALL
INTO BASCHEDULE (SCHEDULE_ID, STARTDATE, ENDDATE) VALUES (20190505,	TO_DATE('5-26-19', 'MM-DD-YY'),	TO_DATE('6-1-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, STARTDATE, ENDDATE) VALUES (20190506,	TO_DATE('6-2-19', 'MM-DD-YY'),	TO_DATE('6-8-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, STARTDATE, ENDDATE) VALUES (20190507,	TO_DATE('6-2-19', 'MM-DD-YY'),	TO_DATE('6-8-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, STARTDATE, ENDDATE) VALUES (20190508,	TO_DATE('6-2-19', 'MM-DD-YY'),	TO_DATE('6-8-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, STARTDATE, ENDDATE) VALUES (20190509,	TO_DATE('6-2-19', 'MM-DD-YY'),	TO_DATE('6-8-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, STARTDATE, ENDDATE) VALUES (20190510,	TO_DATE('6-9-19', 'MM-DD-YY'),	TO_DATE('6-15-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, STARTDATE, ENDDATE) VALUES (20190511,	TO_DATE('6-9-19', 'MM-DD-YY'),	TO_DATE('6-15-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, STARTDATE, ENDDATE) VALUES (20190512,	TO_DATE('6-9-19', 'MM-DD-YY'),	TO_DATE('6-15-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, STARTDATE, ENDDATE) VALUES (20190513,	TO_DATE('6-9-19', 'MM-DD-YY'),	TO_DATE('6-15-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, STARTDATE, ENDDATE) VALUES (20190514,	TO_DATE('6-16-19', 'MM-DD-YY'),	TO_DATE('6-22-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, STARTDATE, ENDDATE) VALUES (20190515,	TO_DATE('6-16-19', 'MM-DD-YY'),	TO_DATE('6-22-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, STARTDATE, ENDDATE) VALUES (20190516,	TO_DATE('6-16-19', 'MM-DD-YY'),	TO_DATE('6-22-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, STARTDATE, ENDDATE) VALUES (20190517,	TO_DATE('6-16-19', 'MM-DD-YY'),	TO_DATE('6-22-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, STARTDATE, ENDDATE) VALUES (20190518,	TO_DATE('6-23-19', 'MM-DD-YY'),	TO_DATE('6-29-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, STARTDATE, ENDDATE) VALUES (20190519,	TO_DATE('6-23-19', 'MM-DD-YY'),	TO_DATE('6-29-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, STARTDATE, ENDDATE) VALUES (20190520,	TO_DATE('6-23-19', 'MM-DD-YY'),	TO_DATE('6-29-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, STARTDATE, ENDDATE) VALUES (20190521,	TO_DATE('6-23-19', 'MM-DD-YY'),	TO_DATE('6-29-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, STARTDATE, ENDDATE) VALUES (20190522,	TO_DATE('6-30-19', 'MM-DD-YY'),	TO_DATE('7-6-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, STARTDATE, ENDDATE) VALUES (20190523,	TO_DATE('6-30-19', 'MM-DD-YY'),	TO_DATE('7-6-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, STARTDATE, ENDDATE) VALUES (20190524,	TO_DATE('6-30-19', 'MM-DD-YY'),	TO_DATE('7-6-19', 'MM-DD-YY'))
INTO BASCHEDULE (SCHEDULE_ID, STARTDATE, ENDDATE) VALUES (20190525,	TO_DATE('6-30-19', 'MM-DD-YY'),	TO_DATE('7-6-19', 'MM-DD-YY'))
SELECT * FROM DUAL;

-- EMPLOYEE_TYPE
INSERT ALL
INTO BAEMPLOYEE_TYPE (EMPLOYEE_TYPE_ID, EMPLOYEE_TYPE_NAME, EMPLOYEE_TYPE_DESCRIPTION) VALUES (1,	'Monk',	'Tenant of the Abbey')
INTO BAEMPLOYEE_TYPE (EMPLOYEE_TYPE_ID, EMPLOYEE_TYPE_NAME, EMPLOYEE_TYPE_DESCRIPTION) VALUES (2,	'Nun',	'Sister of the Church')
INTO BAEMPLOYEE_TYPE (EMPLOYEE_TYPE_ID, EMPLOYEE_TYPE_NAME, EMPLOYEE_TYPE_DESCRIPTION) VALUES (3,	'Layperson',	'Paid Employee')
SELECT * FROM DUAL;
