DROP TABLE STUDENT CASCADE CONSTRAINTS;
DROP TABLE DORM_ROOM CASCADE CONSTRAINTS;
DROP TABLE TEXTBOOK CASCADE CONSTRAINTS;

CREATE TABLE STUDENT
(STUDENT_ID     	number(8) PRIMARY KEY,
STUDENT_FIRST_NAME	varchar(25) NOT NULL,
STUDENT_LAST_NAME	varchar(50) NOT NULL,
STUDENT_TYPE	varchar(1) NOT NULL,
FK_DORM_ROOM_ID	varchar(8));

CREATE TABLE DORM_ROOM
(DORM_ROOM_ID	varchar(8) PRIMARY KEY,
BUILDING_ID	varchar(8) NOT NULL,
COST	decimal(8,2));

CREATE TABLE TEXTBOOK
(TEXTBOOK_ID	varchar(18) PRIMARY KEY,
TEXTBOOK_TITLE	varchar(50) NOT NULL,
FK_STUDENT_ID	number(8));

ALTER TABLE TEXTBOOK
ADD CONSTRAINT FK_STUDENT
FOREIGN KEY(FK_STUDENT_ID)
REFERENCES STUDENT(STUDENT_ID);

ALTER TABLE STUDENT
ADD CONSTRAINT FK_DORM_ROOM
FOREIGN KEY(FK_DORM_ROOM_ID)
REFERENCES DORM_ROOM(DORM_ROOM_ID);



















