drop table product cascade constraints;
drop table customer cascade constraints;
drop table purchase cascade constraints;
drop table inventory cascade constraints;
drop table line_item cascade constraints;

CREATE TABLE PRODUCT
(PRODUCT_ID VARCHAR2(50) PRIMARY KEY,
PRODUCT_NAME VARCHAR2(50) NOT NULL,
PRODUCT_PRICE DECIMAL(6, 2) NOT NULL,
PRODUCT_COST  DECIMAL(6,2));

CREATE TABLE CUSTOMER
(CUSTOMER_ID NUMBER(10) PRIMARY KEY,
CUSTOMER_LNAME VARCHAR2(30) NOT NULL,
CUSTOMER_FNAME VARCHAR2(30) NOT NULL
);

CREATE TABLE PURCHASE
(PURCHASE_ID NUMBER(10) PRIMARY KEY,
PURCHASE_DATE DATE NOT NULL,
FK_CUSTOMER_ID NUMBER(10) NOT NULL,
FOREIGN KEY (FK_CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID));

CREATE TABLE INVENTORY
(INVENTORY_ID VARCHAR2(50) PRIMARY KEY,
QUANTITY_ON_HAND NUMBER(6) NOT NULL,
FK_PRODUCT_ID VARCHAR2(50) NOT NULL,
FOREIGN KEY (FK_PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID));

CREATE TABLE LINE_ITEM
(LINE_ITEM_ID NUMBER(25) PRIMARY KEY,
FK_PRODUCT_ID VARCHAR2(30) NOT NULL,
LINE_ITEM_QUANTITY NUMBER(5),
FK_PURCHASE_ID NUMBER(10) NOT NULL,
FOREIGN KEY (FK_PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID), 
FOREIGN KEY (FK_PURCHASE_ID) REFERENCES PURCHASE(PURCHASE_ID));

INSERT ALL 
INTO CUSTOMER(CUSTOMER_ID, CUSTOMER_LNAME, CUSTOMER_FNAME) VALUES (8000, 'Baratheon', 'Joffrey')
INTO CUSTOMER(CUSTOMER_ID, CUSTOMER_LNAME, CUSTOMER_FNAME) VALUES (8001, 'Lannister', 'Jaime')
INTO CUSTOMER(CUSTOMER_ID, CUSTOMER_LNAME, CUSTOMER_FNAME) VALUES (8002, 'Lannister', 'Tyrion')
INTO CUSTOMER(CUSTOMER_ID, CUSTOMER_LNAME, CUSTOMER_FNAME) VALUES (8003, 'Stark', 'Bran')
INTO CUSTOMER(CUSTOMER_ID, CUSTOMER_LNAME, CUSTOMER_FNAME) VALUES (8004, 'Tarth', 'Brienne')
INTO CUSTOMER(CUSTOMER_ID, CUSTOMER_LNAME, CUSTOMER_FNAME) VALUES (8005, 'Targaryen', 'Daenerys')
SELECT * FROM dual;

INSERT ALL
INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME,PRODUCT_PRICE, PRODUCT_COST) VALUES ('1', 'Eggplant', 2.00, 1.00)
INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE,PRODUCT_COST) VALUES ('2', 'Bible', 20.00,10.00)
INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_COST) VALUES ('3', 'T-Shirt', 25.00,15.00)
INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME,  PRODUCT_PRICE,PRODUCT_COST) VALUES ('4', 'History of Buckfast Abbey', 25.00,15.00)
INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE,PRODUCT_COST) VALUES ('5', 'Cinnamon Candle', 10.00,5.00)
INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE,PRODUCT_COST) VALUES ('6', 'Strawberry Jam', 8.00,4.00)
INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE,PRODUCT_COST) VALUES ('7', 'Buckfast County Guide', 18.00,9.00)
INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE,PRODUCT_COST) VALUES ('8', 'Decorative Cross', 8.00,4.00)
INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE,PRODUCT_COST) VALUES ('9', 'Tote Bag', 6.00,3.00)
INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE,PRODUCT_COST) VALUES ('10', 'A Monks Life',16.00,8.00)
SELECT * FROM dual;


INSERT ALL
INTO PURCHASE(PURCHASE_ID, PURCHASE_DATE,FK_CUSTOMER_ID) VALUES (50, SYSDATE,  8004)
INTO PURCHASE(PURCHASE_ID, PURCHASE_DATE,  FK_CUSTOMER_ID) VALUES (51, SYSDATE,8001)
INTO PURCHASE(PURCHASE_ID, PURCHASE_DATE, FK_CUSTOMER_ID) VALUES (52, SYSDATE,8000)
INTO PURCHASE(PURCHASE_ID, PURCHASE_DATE, FK_CUSTOMER_ID) VALUES (53, SYSDATE, 8003)
INTO PURCHASE(PURCHASE_ID, PURCHASE_DATE,  FK_CUSTOMER_ID) VALUES (54, SYSDATE,8005)
INTO PURCHASE(PURCHASE_ID, PURCHASE_DATE, FK_CUSTOMER_ID) VALUES (55, SYSDATE, 8005)
INTO PURCHASE(PURCHASE_ID, PURCHASE_DATE, FK_CUSTOMER_ID) VALUES (56, SYSDATE, 8003)
INTO PURCHASE(PURCHASE_ID, PURCHASE_DATE, FK_CUSTOMER_ID) VALUES (57, SYSDATE,  8002)
INTO PURCHASE(PURCHASE_ID, PURCHASE_DATE,  FK_CUSTOMER_ID) VALUES (58, SYSDATE,  8000)
INTO PURCHASE(PURCHASE_ID, PURCHASE_DATE, FK_CUSTOMER_ID) VALUES (59, SYSDATE, 8005)
SELECT * FROM dual;

INSERT ALL
INTO LINE_ITEM(LINE_ITEM_ID, FK_PURCHASE_ID, FK_PRODUCT_ID, LINE_ITEM_QUANTITY) VALUES(1, 50, '2', 2)
INTO LINE_ITEM(LINE_ITEM_ID, FK_PURCHASE_ID, FK_PRODUCT_ID, LINE_ITEM_QUANTITY) VALUES(2, 51, '3', 1)
INTO LINE_ITEM(LINE_ITEM_ID, FK_PURCHASE_ID, FK_PRODUCT_ID, LINE_ITEM_QUANTITY) VALUES(3, 52, '1', 2)
INTO LINE_ITEM(LINE_ITEM_ID, FK_PURCHASE_ID, FK_PRODUCT_ID, LINE_ITEM_QUANTITY) VALUES(4, 53, '2', 4)
INTO LINE_ITEM(LINE_ITEM_ID, FK_PURCHASE_ID, FK_PRODUCT_ID, LINE_ITEM_QUANTITY) VALUES(5, 54, '4', 1)
INTO LINE_ITEM(LINE_ITEM_ID, FK_PURCHASE_ID, FK_PRODUCT_ID, LINE_ITEM_QUANTITY) VALUES(6, 55, '5', 4)
INTO LINE_ITEM(LINE_ITEM_ID, FK_PURCHASE_ID, FK_PRODUCT_ID, LINE_ITEM_QUANTITY) VALUES(7, 56, '3', 5)
INTO LINE_ITEM(LINE_ITEM_ID, FK_PURCHASE_ID, FK_PRODUCT_ID, LINE_ITEM_QUANTITY) VALUES(8, 57, '4', 1)
INTO LINE_ITEM(LINE_ITEM_ID, FK_PURCHASE_ID, FK_PRODUCT_ID, LINE_ITEM_QUANTITY) VALUES(9, 58, '1', 8)
INTO LINE_ITEM(LINE_ITEM_ID, FK_PURCHASE_ID, FK_PRODUCT_ID, LINE_ITEM_QUANTITY) VALUES(10, 59, '4', 12)
SELECT * FROM dual;

INSERT ALL
INTO INVENTORY (INVENTORY_ID, QUANTITY_ON_HAND, FK_PRODUCT_ID) VALUES ('PROD01', 50, '1')
INTO INVENTORY (INVENTORY_ID, QUANTITY_ON_HAND, FK_PRODUCT_ID) VALUES ('PROD02', 50, '2')
INTO INVENTORY (INVENTORY_ID, QUANTITY_ON_HAND, FK_PRODUCT_ID) VALUES ('PROD03', 50, '3')
INTO INVENTORY (INVENTORY_ID, QUANTITY_ON_HAND, FK_PRODUCT_ID) VALUES ('PROD04', 50, '4')
INTO INVENTORY (INVENTORY_ID, QUANTITY_ON_HAND, FK_PRODUCT_ID) VALUES ('PROD05', 50, '5')
INTO INVENTORY (INVENTORY_ID, QUANTITY_ON_HAND, FK_PRODUCT_ID) VALUES ('PROD06', 50, '6')
INTO INVENTORY (INVENTORY_ID, QUANTITY_ON_HAND, FK_PRODUCT_ID) VALUES ('PROD07', 50, '7')
INTO INVENTORY (INVENTORY_ID, QUANTITY_ON_HAND, FK_PRODUCT_ID) VALUES ('PROD08', 50, '8')
INTO INVENTORY (INVENTORY_ID, QUANTITY_ON_HAND, FK_PRODUCT_ID) VALUES ('PROD09', 50, '9')
INTO INVENTORY (INVENTORY_ID, QUANTITY_ON_HAND, FK_PRODUCT_ID) VALUES ('PROD10', 50, '10')
SELECT * FROM dual;

COMMIT;