INSERT INTO STUDENT
(STUDENT_ID, STUDENT_FIRST_NAME, STUDENT_LAST_NAME, STUDENT_TYPE, FK_DORM_ROOM_ID)
VALUES
(56789012,'Abraham','Lincoln','R','JKL890');

SELECT STUDENT_ID, STUDENT_FIRST_NAME, STUDENT_LAST_NAME, BUILDING_ID 
	FROM STUDENT
	JOIN DORM_ROOM 
	ON STUDENT.FK_DORM_ROOM_ID=DORM_ROOM.DORM_ROOM_ID;
  
  
Select DORM_ROOM_ID, BUILDING_ID, STUDENT_ID 	
	FROM DORM_ROOM 
	JOIN STUDENT 
	ON STUDENT.FK_DORM_ROOM_ID= DORM_ROOM.DORM_ROOM_ID;  


INSERT INTO TEXTBOOK
(TEXTBOOK_ID, TEXTBOOK_TITLE, FK_STUDENT_ID)
VALUES
('567-89-0012','Abraham Lincoln','00000888');


SELECT TEXTBOOK_TITLE, STUDENT_LAST_NAME
  FROM TEXTBOOK
  JOIN STUDENT
  ON STUDENT.STUDENT_ID = TEXTBOOK.FK_STUDENT_ID;
  
  
SELECT STUDENT_LAST_NAME, TEXTBOOK_TITLE
  FROM STUDENT
  JOIN TEXTBOOK
  ON STUDENT.STUDENT_ID = TEXTBOOK.FK_STUDENT_ID;


SELECT STUDENT_ID, STUDENT_FIRST_NAME, STUDENT_LAST_NAME, TEXTBOOK_TITLE, DORM_ROOM_ID
FROM STUDENT
JOIN TEXTBOOK ON STUDENT.STUDENT_ID = TEXTBOOK.FK_STUDENT_ID
JOIN DORM ON DORM.DORM_ROOM_ID = STUDENT.FK_DORM_ROOM;




--
commit;